"use client";
import Link from "next/link"; import { usePathname } from "next/navigation"; import { signOut } from "next-auth/react";
import { Bell,Car,ChartNoAxesCombined,ChevronDown,Command,LayoutDashboard,Menu,Search,Settings,Users,Wrench,X,LogOut } from "lucide-react"; import { useState } from "react";
import { Button } from "@/components/ui/button"; import { GlobalSearch } from "./global-search";
const nav=[{label:"Dashboard",href:"/command-center",icon:LayoutDashboard},{label:"Customers",href:"/command-center/customers",icon:Users},{label:"Repair Orders",href:"/command-center/repair-orders",icon:Wrench},{label:"Used Cars",href:"/command-center/used-cars",icon:Car},{label:"Reports",href:"/command-center/reports",icon:ChartNoAxesCombined},{label:"Settings",href:"/command-center/settings",icon:Settings}];
export function AppShell({children,user}:{children:React.ReactNode;user:{name?:string|null;role:string}}){const path=usePathname();const [mobile,setMobile]=useState(false);const [search,setSearch]=useState(false);return <div className="cc fixed inset-0 z-[100] flex overflow-hidden bg-[#0c0d0e] text-zinc-100">
 <aside className={`absolute inset-y-0 left-0 z-40 flex w-[250px] flex-col border-r border-white/[.07] bg-[#101112] p-4 transition-transform lg:relative lg:translate-x-0 ${mobile?"translate-x-0":"-translate-x-full"}`}>
  <div className="flex h-14 items-center gap-3 px-2"><div className="grid size-9 place-items-center rounded-xl bg-orange-500 text-white shadow-lg shadow-orange-500/20"><Command size={20}/></div><div><div className="text-sm font-bold tracking-tight">R Complete</div><div className="text-[10px] font-semibold uppercase tracking-[.16em] text-zinc-500">Command Center</div></div><button className="ml-auto lg:hidden" onClick={()=>setMobile(false)} aria-label="Close navigation"><X/></button></div>
  <nav className="mt-6 space-y-1">{nav.map(({label,href,icon:Icon})=>{const active=href==="/command-center"?path===href:path.startsWith(href);return <Link key={href} href={href} onClick={()=>setMobile(false)} className={`flex h-11 items-center gap-3 rounded-xl px-3 text-sm font-medium transition ${active?"bg-white/[.08] text-white shadow-inner":"text-zinc-500 hover:bg-white/[.04] hover:text-zinc-200"}`}><Icon size={18} className={active?"text-orange-400":""}/>{label}{active&&<span className="ml-auto size-1.5 rounded-full bg-orange-400"/>}</Link>})}</nav>
  <div className="mt-auto rounded-2xl border border-white/[.07] bg-white/[.03] p-3"><div className="flex items-center gap-3"><div className="grid size-9 place-items-center rounded-full bg-gradient-to-br from-orange-400 to-red-500 text-xs font-bold">AR</div><div className="min-w-0 flex-1"><p className="truncate text-xs font-semibold text-white !m-0">{user.name}</p><p className="text-[10px] text-zinc-500 !m-0">{user.role.toLowerCase()}</p></div><button onClick={()=>signOut({callbackUrl:"/login"})} className="text-zinc-500 hover:text-white" aria-label="Sign out"><LogOut size={16}/></button></div></div>
 </aside>
 <div className="flex min-w-0 flex-1 flex-col"><header className="flex h-[73px] shrink-0 items-center border-b border-white/[.07] bg-[#0f1011]/90 px-4 backdrop-blur-xl lg:px-7"><Button aria-label="Open navigation" variant="ghost" size="icon" className="lg:hidden" onClick={()=>setMobile(true)}><Menu/></Button><div className="ml-2 lg:ml-0"><p className="text-[10px] font-semibold uppercase tracking-[.14em] text-zinc-600 !m-0">Thursday, July 9</p><h1 className="text-base font-semibold text-white !m-0">Good afternoon, Alex</h1></div><div className="ml-auto flex items-center gap-2"><button onClick={()=>setSearch(true)} className="hidden h-10 w-64 items-center gap-2 rounded-xl border border-white/[.08] bg-white/[.03] px-3 text-left text-xs text-zinc-600 transition hover:border-white/15 md:flex"><Search size={15}/>Search anything…<kbd className="ml-auto rounded border border-white/10 px-1.5 py-0.5 text-[9px]">⌘ K</kbd></button><Button aria-label="Open search" variant="ghost" size="icon" onClick={()=>setSearch(true)} className="md:hidden"><Search size={18}/></Button><Button aria-label="View notifications" variant="ghost" size="icon" className="relative"><Bell size={18}/><span className="absolute right-2 top-2 size-2 rounded-full border-2 border-[#0f1011] bg-orange-400"/></Button><button aria-label="Open user profile" className="hidden items-center gap-2 pl-2 text-xs font-semibold sm:flex"><div className="grid size-8 place-items-center rounded-full bg-orange-500">AR</div><ChevronDown size={13} className="text-zinc-500"/></button></div></header>
 <main className="min-w-0 flex-1 overflow-y-auto bg-[radial-gradient(circle_at_60%_-20%,rgba(249,115,22,.07),transparent_35%)] p-4 lg:p-7">{children}</main></div>{search&&<GlobalSearch onClose={()=>setSearch(false)}/>}</div>}
