export const HONDA_HUB_SLUG = "honda-repair-crown-point-in";
export const HONDA_BASE_URL = "https://www.rcompleteautocare.com";

export type HondaFaq = { question: string; answer: string };

export type HondaPageData = {
  slug: string;
  shortName: string;
  title: string;
  description: string;
  eyebrow: string;
  heading: string;
  intro: string;
  problems: string[];
  warningSigns: string[];
  diagnostic: string;
  services: string[];
  maintenance: string;
  driving: string;
  timing: string;
  cost: string;
  warranty: string;
  related: string[];
  faqs: HondaFaq[];
  kind: "model" | "service";
};

const modelFaqs = (model: string, concerns: [string, string, string]): HondaFaq[] => [
  { question: `What ${model} warning signs should I have checked promptly?`, answer: `New warning lights, overheating, fluid loss, harsh shifting, braking changes, persistent vibration, or a sudden change in how your ${model} runs should be inspected promptly. If the vehicle feels unsafe, stop driving and call us.` },
  { question: `Can you diagnose a ${model} check-engine light without replacing parts first?`, answer: `Yes. On a ${model}, the stored code begins the investigation; it does not select a replacement part. We compare scan information with the vehicle’s history and symptoms, then test the indicated circuit or mechanical system before proposing work.` },
  { question: `Can I keep driving my ${model} with a warning light on?`, answer: `The answer for a ${model} depends on which warning appeared and how the vehicle behaves. Stop safely for a flashing engine light, oil-pressure warning, high temperature, unsafe braking, or severe shaking. Call the shop when the severity is unclear.` },
  { question: `How long does ${model} diagnosis or repair take?`, answer: `${model} testing time changes with the symptom, access, and whether the fault appears consistently. Once we identify the cause, parts availability and related conditions determine repair time; we give you that plan before work is authorized.` },
  { question: `What affects the cost of a ${model} repair?`, answer: `A ${model} estimate reflects its year, powertrain and drivetrain, the tests needed, component access, parts selection, and any connected damage. Diagnosis comes first so the estimate addresses the demonstrated fault.` },
  { question: `Do you help with extended warranty claims for a ${model}?`, answer: `Yes. For a potentially covered ${model} failure, we can record test results, contact the warranty administrator, and respond to documentation requests. The customer’s contract decides coverage and authorization.` },
  { question: `Do you use quality parts for ${model} repairs?`, answer: `${model} parts are selected for the confirmed repair and exact configuration, with attention to quality, fit, and availability. We discuss the recommended option with you before ordering or installing it.` },
  { question: `Does every ${model} have the same maintenance schedule?`, answer: `No. ${model} maintenance changes across model years, engines, transmissions, drivetrains, usage, and prior service. The owner’s manual and vehicle-specific information guide what is actually due.` },
  { question: concerns[0], answer: concerns[1] },
  { question: `How do I schedule ${model} service in Crown Point?`, answer: `Choose a time through Book Appointment or call (219) 262-2711 for your ${model}. Sharing its year, mileage, dashboard messages, and when the symptom happens helps us prepare for the visit.` },
];

const serviceFaqs = (service: string, detail: [string, string, string]): HondaFaq[] => [
  { question: `What symptoms suggest my Honda may need ${service.toLowerCase()}?`, answer: detail[1] },
  { question: `How do you diagnose a Honda before recommending ${service.toLowerCase()}?`, answer: detail[2] },
  { question: `Can I keep driving before my Honda is inspected?`, answer: `Driving before ${service.toLowerCase()} diagnosis depends on the reported condition. Overheating, lost oil pressure, compromised brakes, severe mechanical noise, or a flashing engine light means stop safely and call.` },
  { question: `How long can Honda ${service.toLowerCase()} take?`, answer: `Honda ${service.toLowerCase()} timing follows the exact configuration, test findings, component access, and parts availability. Related damage can expand the scope, so we set expectations after inspection rather than guessing beforehand.` },
  { question: `What affects Honda ${service.toLowerCase()} cost?`, answer: `Cost for Honda ${service.toLowerCase()} reflects the model and powertrain, diagnostic depth, failed component, access, parts selection, and connected damage. Testing prevents a generic quote from being mistaken for a repair plan.` },
  { question: `Could extended warranty coverage apply?`, answer: `A contract may cover the failure behind Honda ${service.toLowerCase()}, depending on its terms and exclusions. We can submit the documented findings, while the administrator makes the authorization decision.` },
  { question: `Will you explain parts options before the repair?`, answer: `Yes. After Honda ${service.toLowerCase()} testing identifies the cause, we explain the proposed work and suitable parts before requesting approval.` },
  { question: `Do all Honda models use the same components or service interval?`, answer: `No. The components and guidance relevant to ${service.toLowerCase()} vary across Honda models, years, engines, transmissions, and drivetrains. We identify the vehicle before applying service information.` },
  { question: detail[0], answer: detail[1] },
  { question: `How do I book Honda ${service.toLowerCase()} in Crown Point?`, answer: `Schedule Honda ${service.toLowerCase()} online or call (219) 262-2711. Provide the model, year, mileage, warning messages, and the conditions that make the symptom appear.` },
];

const models: HondaPageData[] = [
  {
    slug: "honda-civic-repair-crown-point-in", shortName: "Honda Civic", kind: "model",
    title: "Honda Civic Repair Crown Point, IN | R Complete Auto Care",
    description: "Honda Civic diagnostics and repair in Crown Point, IN for CVT symptoms, A/C concerns, vibration, warning lights, brakes, and suspension.",
    eyebrow: "Honda Civic service in Crown Point", heading: "Honda Civic Repair and Diagnostics",
    intro: "A Civic can be economical and dependable while still requiring careful diagnosis when a warning light, vibration, cooling problem, or transmission symptom appears. We identify the vehicle configuration and test the system before recommending parts.",
    problems: ["CVT shudder, delayed response, noise, or warning messages on applicable models", "Weak or intermittent A/C performance", "Engine-mount vibration at idle or when shifting into gear", "Starter, battery, alternator, and charging concerns", "Check-engine-light, suspension-noise, and brake-wear concerns"],
    warningSigns: ["Flashing check-engine light or pronounced misfire", "Temperature gauge rising or coolant loss", "Delayed engagement, severe shudder, or transmission warning", "Grinding brakes, pulling, or a changing pedal", "Slow cranking, repeated jump starts, or charging warning"],
    diagnostic: "We start with the driver’s description, model year, service history, and a road test when safe. Depending on the concern, testing may include scan and freeze-frame data, charging-system measurements, A/C temperature and pressure evaluation, mount inspection, brake measurements, or suspension checks.",
    services: ["Engine and electrical diagnostics", "CVT and automatic-transmission diagnosis", "A/C and heating repair", "Engine mounts and vibration diagnosis", "Brake, steering, and suspension service", "Maintenance based on the specific Civic"],
    maintenance: "Civic maintenance depends on year, engine, transmission, mileage, and driving conditions. Follow the owner’s manual and vehicle-specific maintenance information rather than a generic schedule; fluid type is especially important for applicable CVTs.",
    driving: "A steady warning light with normal operation may allow a short trip for diagnosis, but flashing lights, overheating, oil-pressure warnings, severe shaking, or unsafe braking require stopping.",
    timing: "Straightforward inspections may be completed the same day. Intermittent electrical, A/C, or CVT concerns can require additional testing, while repair time depends on access and parts availability.",
    cost: "Cost changes with generation, engine and transmission, diagnostic time, parts access, and whether one failure has affected another component.",
    warranty: "For potentially covered Civic failures, we can provide findings and documentation to the extended warranty administrator and help with the claim process.",
    related: ["honda-transmission-repair-crown-point-in", "honda-check-engine-light-diagnostics-crown-point-in", "honda-ac-repair-crown-point-in"],
    faqs: modelFaqs("Honda Civic", ["Does every Honda Civic use a CVT?", "No. Transmission type varies by year, trim, and configuration. We identify the exact transmission before testing or selecting fluid.", "civic"]),
  },
  {
    slug: "honda-accord-repair-crown-point-in", shortName: "Honda Accord", kind: "model",
    title: "Honda Accord Repair Crown Point, IN | R Complete Auto Care",
    description: "Honda Accord repair in Crown Point for turbo engine concerns, leaks, timing noise, transmission symptoms, A/C, brakes, and suspension.",
    eyebrow: "Honda Accord service in Crown Point", heading: "Honda Accord Repair and Diagnostics",
    intro: "Accord systems vary substantially across generations, from naturally aspirated engines and conventional automatics to turbocharged engines and CVTs. Accurate identification and testing matter more than assumptions based on the model name alone.",
    problems: ["Oil leaks or consumption concerns", "Cold-start timing or VTC-related noise on applicable engines", "Turbocharged-engine drivability concerns on equipped models", "Automatic-transmission or CVT symptoms", "A/C, brake, steering, and suspension wear"],
    warningSigns: ["Low oil level, oil smell, or visible leakage", "Persistent start-up rattle or new engine noise", "Loss of power, misfire, smoke, or overheating", "Harsh shifting, shudder, or delayed engagement", "Brake vibration, pulling, or suspension clunking"],
    diagnostic: "We match the Accord’s VIN-level configuration to the symptom, review scan and freeze-frame data, inspect fluid condition and leaks, road test when safe, and perform circuit, pressure, mechanical, or compression-related tests when the evidence calls for them.",
    services: ["Engine, timing, and oil-leak diagnosis", "Turbocharger-system testing where equipped", "Automatic and CVT diagnosis", "A/C and electrical repair", "Brake and suspension service", "Vehicle-specific maintenance"],
    maintenance: "The appropriate maintenance plan depends on Accord generation, engine, transmission, mileage, use, and history. Owner’s-manual and vehicle-specific information should guide fluid and component service.",
    driving: "Do not continue driving with overheating, low oil pressure, severe misfire, pronounced transmission slip, or compromised braking. Milder symptoms still deserve timely inspection before they become more disruptive.",
    timing: "Oil-leak, noise, or drivability diagnosis may be same-day or require extended observation. Repair timing depends on the confirmed cause and parts access.",
    cost: "Engine configuration, turbo equipment, transmission type, leak location, testing time, and related wear all influence the estimate.",
    warranty: "We assist with extended warranty documentation and authorization when an Accord failure may qualify under the customer’s contract.",
    related: ["honda-engine-repair-crown-point-in", "honda-transmission-repair-crown-point-in", "honda-ac-repair-crown-point-in"],
    faqs: modelFaqs("Honda Accord", ["Do all Honda Accords have turbocharged engines?", "No. Engine choices vary by generation and trim. Turbo-specific testing only applies to equipped vehicles.", "accord"]),
  },
  {
    slug: "honda-cr-v-repair-crown-point-in", shortName: "Honda CR-V", kind: "model",
    title: "Honda CR-V Repair Crown Point, IN | R Complete Auto Care",
    description: "Honda CR-V diagnostics in Crown Point for turbo, CVT, AWD, catalytic-efficiency, A/C, suspension, and oil-related concerns.",
    eyebrow: "Honda CR-V service in Crown Point", heading: "Honda CR-V Repair and Diagnostics",
    intro: "CR-V generations use different engines, transmissions, and drivetrains. We separate configuration-specific concerns from general symptoms and verify the actual failure before recommending a repair.",
    problems: ["Turbocharger or oil-dilution concerns on certain equipped model years", "Catalytic-converter efficiency or emissions faults", "CVT noise, shudder, or response concerns", "AWD drivetrain noise, vibration, or fluid-service questions", "A/C performance and suspension noise"],
    warningSigns: ["Fuel smell in oil, rising oil level, or poor running", "Flashing check-engine light or reduced power", "Drivetrain binding, vibration, or warning messages", "Overheating or loss of cabin cooling", "Clunks, unstable handling, or abnormal tire wear"],
    diagnostic: "Testing can include scan and freeze-frame review, fuel-trim and misfire data, oil and coolant inspection, exhaust or catalyst evaluation, CVT road testing, AWD inspection, and A/C or suspension measurements as appropriate.",
    services: ["Engine and turbo-system diagnostics where applicable", "CVT diagnosis and service", "AWD drivetrain inspection", "Check-engine-light and emissions diagnosis", "A/C repair", "Brake and suspension service"],
    maintenance: "CR-V maintenance varies by year, engine, CVT or automatic transmission, AWD equipment, and driving pattern. We use the owner’s manual and vehicle-specific information rather than assuming every CR-V needs the same work.",
    driving: "Stop for overheating, oil-pressure warnings, flashing check-engine lights, severe drivetrain vibration, or unsafe handling. Ask us about steady warning lights or mild symptoms before a longer trip.",
    timing: "Intermittent catalyst, turbo, CVT, or AWD symptoms may take more diagnostic time than a visible wear item. Repair timing follows the confirmed cause.",
    cost: "Engine and drivetrain configuration, diagnostic depth, parts access, and whether the concern is electrical, mechanical, or maintenance-related determine cost.",
    warranty: "We can document eligible CR-V failures and coordinate with an extended warranty company while keeping you informed about the contract decision.",
    related: ["honda-transmission-repair-crown-point-in", "honda-engine-repair-crown-point-in", "honda-check-engine-light-diagnostics-crown-point-in"],
    faqs: modelFaqs("Honda CR-V", ["Do oil-dilution or turbo concerns apply to every Honda CR-V?", "No. They are configuration- and model-year-specific possibilities, not conditions affecting every CR-V. Diagnosis must begin with the exact vehicle and symptoms.", "crv"]),
  },
  {
    slug: "honda-pilot-repair-crown-point-in", shortName: "Honda Pilot", kind: "model",
    title: "Honda Pilot Repair Crown Point, IN | R Complete Auto Care",
    description: "Honda Pilot repair in Crown Point for timing-belt maintenance, misfires, transmission concerns, oil leaks, steering, and suspension.",
    eyebrow: "Honda Pilot service in Crown Point", heading: "Honda Pilot Repair and Diagnostics",
    intro: "A Pilot’s family-hauling and all-weather duties can make drivability, braking, and maintenance concerns especially important. We verify the engine, transmission, and drivetrain configuration before planning service.",
    problems: ["Timing-belt maintenance on applicable engines", "Misfires or VCM-related symptoms on applicable configurations", "Transmission shift quality, shudder, or warning lights", "Oil leaks and cooling-system concerns", "Steering, suspension, brake, and AWD wear"],
    warningSigns: ["Misfire, flashing check-engine light, or loss of power", "Timing-area noise or overdue vehicle-specific belt service", "Harsh shifts, delayed engagement, or overheating message", "Oil or coolant loss", "Loose steering, clunks, pulling, or braking changes"],
    diagnostic: "We combine scan data, road testing, leak inspection, ignition and mechanical checks, transmission evaluation, and steering or suspension measurements. VCM or timing-related possibilities are treated as hypotheses until testing supports them.",
    services: ["Timing-belt system service where applicable", "Misfire and engine diagnostics", "Transmission diagnosis", "Oil-leak and cooling-system repair", "AWD, brake, steering, and suspension service", "Maintenance review"],
    maintenance: "Pilot maintenance depends on model year, engine, transmission, drivetrain, towing or load use, and history. The exact engine determines whether timing-belt service applies.",
    driving: "A flashing light, overheating, low oil pressure, major transmission slip, or unsafe steering or braking means stop. Do not postpone a known timing-belt service without checking the vehicle-specific guidance.",
    timing: "A planned maintenance visit is usually easier to schedule than an intermittent misfire or transmission diagnosis. We provide timing after the inspection and parts check.",
    cost: "Timing-system scope, engine access, transmission type, AWD equipment, diagnostic time, and related wear shape the estimate.",
    warranty: "If a Pilot repair may be covered, we can communicate test results and required documentation to the extended warranty administrator.",
    related: ["honda-timing-belt-service-crown-point-in", "honda-transmission-repair-crown-point-in", "honda-engine-repair-crown-point-in"],
    faqs: modelFaqs("Honda Pilot", ["Does every Honda Pilot need timing-belt service?", "Timing-system design and service guidance depend on the exact engine and model year. We verify the vehicle before making a maintenance recommendation.", "pilot"]),
  },
  {
    slug: "honda-odyssey-repair-crown-point-in", shortName: "Honda Odyssey", kind: "model",
    title: "Honda Odyssey Repair Crown Point, IN | R Complete Auto Care",
    description: "Honda Odyssey diagnostics in Crown Point for sliding doors, timing belts, misfires, transmissions, mounts, A/C, brakes, and suspension.",
    eyebrow: "Honda Odyssey service in Crown Point", heading: "Honda Odyssey Repair and Diagnostics",
    intro: "An Odyssey combines powertrain systems with sliding-door electronics, multi-zone climate control, and family-focused comfort features. A structured diagnosis helps avoid replacing expensive assemblies based on symptoms alone.",
    problems: ["Power sliding-door electrical, latch, cable, or sensor concerns", "Timing-belt maintenance on applicable engines", "Misfires and engine-mount vibration", "Transmission shift or shudder symptoms", "Front and rear A/C, brakes, and suspension concerns"],
    warningSigns: ["Door reverses, will not latch, or operates unexpectedly", "Flashing check-engine light or pronounced vibration", "Transmission slipping, delayed engagement, or warning message", "Overheating or poor cooling from one climate zone", "Brake grinding, pulling, or suspension instability"],
    diagnostic: "We isolate door mechanical and electrical inputs, review powertrain scan data, inspect mounts and timing-service history, road test transmission symptoms, and test the appropriate A/C zone or chassis component.",
    services: ["Sliding-door electrical diagnosis", "Timing-belt service where applicable", "Misfire and engine-mount diagnosis", "Transmission diagnosis", "Front and rear A/C repair", "Brake and suspension service"],
    maintenance: "Odyssey maintenance is specific to model year, engine, transmission, mileage, and use. Frequent short trips, passenger loads, and service history can affect priorities; consult the owner’s manual for the exact vehicle.",
    driving: "Do not drive with an unlatched door, unsafe brakes, overheating, low oil pressure, severe misfire, or major transmission slip. Other electrical issues may allow driving but should be assessed before daily use.",
    timing: "Door and intermittent electrical diagnosis can require extra testing. Planned timing-belt work and confirmed mechanical repairs can be scheduled once parts and scope are known.",
    cost: "Door-system cause, engine access, transmission diagnosis, number of A/C zones, and related mechanical wear affect the estimate.",
    warranty: "We can assist with extended warranty claims for covered Odyssey failures, including diagnostic documentation and administrator communication.",
    related: ["honda-timing-belt-service-crown-point-in", "honda-transmission-repair-crown-point-in", "honda-ac-repair-crown-point-in"],
    faqs: modelFaqs("Honda Odyssey", ["Is every Odyssey sliding-door problem an electrical failure?", "No. Latches, rollers, cables, alignment, sensors, switches, wiring, and control inputs can create similar symptoms, so the door should be tested before parts are selected.", "odyssey"]),
  },
  {
    slug: "honda-ridgeline-repair-crown-point-in", shortName: "Honda Ridgeline", kind: "model",
    title: "Honda Ridgeline Repair Crown Point, IN | R Complete Auto Care",
    description: "Honda Ridgeline repair in Crown Point for AWD service, timing belts, suspension, transmissions, oil leaks, brakes, and towing maintenance.",
    eyebrow: "Honda Ridgeline service in Crown Point", heading: "Honda Ridgeline Repair and Diagnostics",
    intro: "Ridgeline maintenance and diagnosis should account for its drivetrain, truck use, cargo or towing demands, and exact generation. We inspect the system under concern rather than treating it like a generic pickup.",
    problems: ["AWD drivetrain fluid, noise, or vibration concerns", "Timing-belt maintenance on applicable engines", "Transmission shift quality or temperature concerns", "Oil leaks and cooling-system issues", "Suspension, steering, and brake wear under load"],
    warningSigns: ["Drivetrain binding, vibration, or warning message", "Overheating while towing or carrying load", "Harsh shifts, slipping, or delayed engagement", "Oil or coolant loss", "Brake fade, pulling, clunking, or unstable handling"],
    diagnostic: "We ask how the Ridgeline is used, including trailer weight patterns, cargo, trip length, and whether a symptom appears only under load. A safe road test is paired with drivetrain-fluid inspection, module scan data, cooling-system review, timing-service history, and measured brake or suspension wear. This helps distinguish a powertrain fault from a wheel, tire, mount, chassis, or maintenance condition before the truck returns to hauling duty.",
    services: ["AWD drivetrain inspection and service", "Timing-belt service where applicable", "Transmission diagnosis", "Oil-leak and cooling-system repair", "Brake and suspension service", "Towing-related maintenance review"],
    maintenance: "Towing, short trips, load, road conditions, model year, and drivetrain all affect maintenance. Follow the owner’s manual and vehicle-specific severe-use guidance where it applies.",
    driving: "Stop for overheating, low oil pressure, severe transmission slip, unsafe brakes, or pronounced drivetrain binding. Have new load-related symptoms checked before towing again.",
    timing: "Maintenance services can be planned, while intermittent vibration or towing-temperature complaints may require road testing and more diagnostic time.",
    cost: "AWD configuration, load-related wear, timing-system scope, transmission type, testing time, and parts access determine cost.",
    warranty: "We help document covered Ridgeline failures for extended warranty review and explain what the administrator authorizes.",
    related: ["honda-timing-belt-service-crown-point-in", "honda-transmission-repair-crown-point-in", "honda-brake-repair-crown-point-in"],
    faqs: modelFaqs("Honda Ridgeline", ["Should towing change my Ridgeline maintenance plan?", "It can. Load, trip length, temperature, and frequency matter. Use the owner’s manual and vehicle-specific severe-use information, and tell us how the truck is used.", "ridgeline"]),
  },
  {
    slug: "honda-hr-v-repair-crown-point-in", shortName: "Honda HR-V", kind: "model",
    title: "Honda HR-V Repair Crown Point, IN | R Complete Auto Care",
    description: "Honda HR-V service in Crown Point for CVT symptoms, AWD concerns, brakes, suspension noise, charging problems, and A/C performance.",
    eyebrow: "Honda HR-V service in Crown Point", heading: "Honda HR-V Repair and Diagnostics",
    intro: "HR-V symptoms can cross between engine, CVT, AWD, electrical, and chassis systems. We confirm the model year and drivetrain, reproduce the concern when possible, and test before recommending service.",
    problems: ["CVT noise, shudder, response, or warning concerns", "AWD vibration, binding, or maintenance questions", "Brake wear and pedal changes", "Suspension clunks or uneven tire wear", "Battery, charging, starting, and A/C performance problems"],
    warningSigns: ["Transmission or AWD warning message", "Delayed response, severe shudder, or new drivetrain noise", "Repeated dead battery or charging warning", "Brake grinding, pulling, or soft pedal", "Overheating, weak cooling, or unstable handling"],
    diagnostic: "We review scan data, battery and charging measurements, CVT or AWD behavior, fluid condition, suspension and brake measurements, and A/C operation based on the reported symptom.",
    services: ["CVT and AWD diagnosis", "Battery and charging-system testing", "Brake and suspension repair", "A/C diagnosis and repair", "Check-engine-light diagnosis", "Vehicle-specific maintenance"],
    maintenance: "HR-V model years and drivetrains do not all share one schedule. Correct CVT and AWD service information and fluid selection depend on the exact vehicle.",
    driving: "Stop for unsafe brakes, overheating, severe drivetrain behavior, low oil pressure, or a flashing warning light. Address recurring battery or charging symptoms before the vehicle leaves you stranded.",
    timing: "Battery and visible wear checks may be quick; intermittent electrical, CVT, or AWD issues can require longer testing. We explain timing after initial diagnosis.",
    cost: "Drivetrain configuration, diagnostic time, fluid or component requirements, parts access, and related wear all affect the repair estimate.",
    warranty: "We can help document HR-V component failures for an extended warranty claim when the customer’s contract may apply.",
    related: ["honda-transmission-repair-crown-point-in", "honda-brake-repair-crown-point-in", "honda-ac-repair-crown-point-in"],
    faqs: modelFaqs("Honda HR-V", ["Does every HR-V have AWD?", "No. Drivetrain varies by year and trim. AWD-specific service and diagnosis apply only to equipped vehicles.", "hrv"]),
  },
  {
    slug: "honda-passport-repair-crown-point-in", shortName: "Honda Passport", kind: "model",
    title: "Honda Passport Repair Crown Point, IN | R Complete Auto Care",
    description: "Honda Passport repair in Crown Point for timing-belt maintenance, AWD, transmission symptoms, suspension, brakes, and A/C concerns.",
    eyebrow: "Honda Passport service in Crown Point", heading: "Honda Passport Repair and Diagnostics",
    intro: "Passport service requires attention to the exact engine, transmission, and AWD configuration plus how the vehicle is used. We combine road testing, scan data, and physical inspection to identify the real cause.",
    problems: ["Timing-belt maintenance on applicable engines", "AWD drivetrain noise, vibration, or fluid concerns", "Transmission shift quality or warning messages", "Suspension and steering wear", "Brake service and A/C performance"],
    warningSigns: ["Harsh shifting, delayed engagement, or drivetrain warning", "Binding, vibration, or new noise in turns", "Brake vibration, pulling, or pedal change", "Suspension clunk, wandering, or uneven tire wear", "Overheating, oil-pressure warning, or weak A/C"],
    diagnostic: "For a Passport, we document whether the concern changes during turns, highway cruising, rough-road travel, braking, or climate-control use. We then verify timing-service history, scan powertrain and AWD modules, inspect drivetrain fluids and leaks, and reproduce the condition on a controlled road test. Brake measurements, steering and suspension checks, tire condition, and A/C temperature testing are added according to what the driver experiences.",
    services: ["Timing-belt service where applicable", "AWD and transmission diagnosis", "Brake, steering, and suspension repair", "A/C repair", "Engine and electrical diagnostics", "Maintenance review"],
    maintenance: "Passport service varies by model year, mileage, use, and configuration. Owner’s-manual information should guide timing, drivetrain, and fluid service rather than a universal schedule.",
    driving: "Stop for overheating, low oil pressure, severe drivetrain behavior, or unsafe braking and steering. New AWD or transmission symptoms should be checked before a long trip.",
    timing: "Planned maintenance can be scheduled predictably. Intermittent AWD, transmission, or A/C symptoms may require additional diagnostic time.",
    cost: "Timing-system scope, AWD or transmission configuration, diagnostic effort, parts access, and related wear affect cost.",
    warranty: "We can work with an extended warranty administrator on covered Passport repairs and provide the requested diagnostic information.",
    related: ["honda-timing-belt-service-crown-point-in", "honda-transmission-repair-crown-point-in", "honda-brake-repair-crown-point-in"],
    faqs: modelFaqs("Honda Passport", ["Does every Passport maintenance visit include AWD service?", "No. AWD service depends on equipment, mileage, history, use, and vehicle-specific guidance. We review those details first.", "passport"]),
  },
];

const services: HondaPageData[] = [
  {
    slug: "honda-timing-belt-service-crown-point-in", shortName: "Honda Timing Belt Service", kind: "service",
    title: "Honda Timing Belt Service Crown Point | R Complete Auto Care",
    description: "Honda timing belt inspection and service in Crown Point with vehicle-specific guidance for belts, tensioners, idlers, water pumps, and seals.",
    eyebrow: "Vehicle-specific Honda maintenance", heading: "Honda Timing Belt Service",
    intro: "Not every Honda engine uses a timing belt, and there is no single replacement interval for every Honda. The exact model year, engine, mileage, service history, and manufacturer information must be identified first.",
    problems: ["Unknown or overdue timing-belt service history", "Timing-cover oil or coolant leakage", "Noise from the timing-belt area", "Aging tensioner or idler components", "Water-pump concerns discovered during inspection"],
    warningSigns: ["Documented interval is approaching with no service record", "New timing-area noise", "Oil or coolant visible near the timing covers", "Overheating or coolant loss", "Engine performance change requiring diagnosis"],
    diagnostic: "We identify the engine and applicable service information, review records, inspect accessible areas for leakage or noise, and determine the correct service scope. Timing-belt condition cannot always be judged by a quick external glance.",
    services: ["Timing belt", "Tensioner and idler components", "Water pump when appropriate to the service plan", "Related seals and leak inspection", "Drive-belt and cooling-system inspection", "Post-service verification"],
    maintenance: "Use the owner’s manual and vehicle-specific maintenance information. Driving conditions, age, mileage, and prior work matter; we do not publish one interval for every Honda engine.",
    driving: "A known overdue belt should be addressed promptly. Some Honda engines are interference designs, where loss of valve timing can cause internal damage, but risk depends on the exact engine and condition. We explain this without assuming failure is imminent.",
    timing: "Timing-belt service is planned work whose duration depends on engine access and the related components included. We confirm scope and parts before scheduling.",
    cost: "Engine configuration, access, included tensioner/idlers, water pump, seals, fluid needs, and discovered leakage affect cost.",
    warranty: "Routine maintenance is often excluded from extended warranties, while a covered component failure may be treated differently. The contract controls coverage.",
    related: ["honda-pilot-repair-crown-point-in", "honda-odyssey-repair-crown-point-in", "honda-ridgeline-repair-crown-point-in"],
    faqs: serviceFaqs("Timing Belt Service", ["Do all Honda engines use a timing belt?", "No. Honda has used both timing belts and timing chains. The exact model year and engine determine the design and applicable maintenance guidance.", "We identify the engine, review service records and vehicle-specific information, and inspect for related leaks or noise before defining the belt, tensioner, idler, water-pump, and seal scope."]),
  },
  {
    slug: "honda-transmission-repair-crown-point-in", shortName: "Honda Transmission Repair", kind: "service",
    title: "Honda Transmission Repair Crown Point | R Complete Auto Care",
    description: "Honda automatic transmission and CVT diagnostics in Crown Point for slipping, shuddering, delayed engagement, overheating, noise, and warning lights.",
    eyebrow: "Automatic and CVT diagnosis", heading: "Honda Transmission Repair and Diagnostics",
    intro: "Honda vehicles use different conventional automatic transmissions and CVTs. A shudder or delayed response can have fluid, electrical, control, driveline, or internal mechanical causes, so testing comes before a repair recommendation.",
    problems: ["Slipping or engine speed flare", "Shuddering or vibration", "Delayed or harsh engagement", "Overheating or warning lights", "Whining, grinding, or other new noise"],
    warningSigns: ["Vehicle will not engage a gear", "Severe slip or loss of acceleration", "Overheating warning or burning odor", "Metallic noise", "Transmission warning with reduced operation"],
    diagnostic: "We confirm the transmission type, scan for codes and live data, inspect fluid level and condition using the correct procedure, road test when safe, evaluate mounts and driveline influences, and perform mechanical verification when indicated.",
    services: ["Automatic-transmission diagnosis", "CVT diagnosis", "Electrical and solenoid-circuit testing", "Fluid-condition and leak inspection", "Driveline and mount inspection", "Repair or replacement planning based on evidence"],
    maintenance: "Correct fluid and service information depend on the exact transmission. A fluid service can be appropriate maintenance, but it is not a promise to repair an existing internal failure.",
    driving: "Continued driving with severe slip, overheating, delayed engagement into traffic, or loss of drive can be unsafe and may worsen damage. Stop and call for guidance.",
    timing: "Road testing and scan diagnosis may be completed promptly, while intermittent faults or internal verification can take longer. Major repair timing depends on the confirmed plan and parts.",
    cost: "Transmission type, diagnostic time, electrical versus internal cause, fluid condition, access, and whether repair or replacement is justified affect cost.",
    warranty: "We regularly document transmission findings for extended warranty review. Approval, teardown authorization, and covered parts depend on the contract.",
    related: ["honda-civic-repair-crown-point-in", "honda-accord-repair-crown-point-in", "honda-cr-v-repair-crown-point-in"],
    faqs: serviceFaqs("Transmission Repair", ["Will a Honda transmission fluid service fix slipping or shuddering?", "Not necessarily. Service may be appropriate maintenance, but internal wear, control faults, mounts, or other problems require diagnosis and will not be repaired by fluid alone.", "We identify the transmission, inspect fluid condition and leaks, review codes and live data, road test safely, and verify electrical, driveline, or mechanical causes before recommending work."]),
  },
  {
    slug: "honda-engine-repair-crown-point-in", shortName: "Honda Engine Repair", kind: "service",
    title: "Honda Engine Repair Crown Point, IN | R Complete Auto Care",
    description: "Honda engine diagnostics and repair in Crown Point for overheating, oil use, leaks, misfires, timing, compression, turbo, and internal damage concerns.",
    eyebrow: "Test before major repair", heading: "Honda Engine Repair and Diagnostics",
    intro: "An engine symptom does not automatically mean the engine needs replacement. We test cooling, lubrication, ignition, fuel, timing, compression, electrical, and turbo-related systems where applicable before discussing a major repair.",
    problems: ["Overheating or coolant loss", "Oil consumption or external leaks", "Misfires and rough running", "Compression or timing concerns", "Turbocharger-system concerns on equipped engines", "Internal noise or damage"],
    warningSigns: ["Oil-pressure or temperature warning", "Flashing check-engine light", "Heavy smoke, severe knock, or sudden power loss", "Rapid coolant or oil loss", "Repeated misfire or stalling"],
    diagnostic: "Testing may include scan and freeze-frame analysis, cooling-system pressure checks, leak inspection, ignition and fuel testing, relative or manual compression tests, leak-down testing, timing verification, oil-pressure checks, or turbo-system evaluation as evidence requires.",
    services: ["Overheating diagnosis", "Oil-leak and consumption evaluation", "Misfire diagnosis", "Timing and compression testing", "Turbo-system diagnosis where equipped", "Internal repair or replacement recommendations only after testing"],
    maintenance: "Oil specification, change interval, coolant service, valve or timing maintenance, and other needs vary by engine and model year. Use Honda’s vehicle-specific information and actual service history.",
    driving: "Stop immediately for low oil pressure, overheating, heavy mechanical knock, severe smoke, or a flashing check-engine light. Continuing can turn a repairable problem into internal damage.",
    timing: "Initial testing can be same-day, but intermittent overheating, oil use, or internal mechanical diagnosis may require additional time. Major work is scheduled after findings and authorization.",
    cost: "Test time, engine configuration, access, extent of damage, machining or replacement needs, parts availability, and related cooling or lubrication failures affect cost.",
    warranty: "For potentially covered engine failures, we can provide diagnostic results and communicate with the extended warranty administrator before authorized work.",
    related: ["honda-check-engine-light-diagnostics-crown-point-in", "honda-timing-belt-service-crown-point-in", "honda-accord-repair-crown-point-in"],
    faqs: serviceFaqs("Engine Repair", ["Does an overheating or misfiring Honda automatically need an engine?", "No. Cooling-system, ignition, fuel, sensor, wiring, timing, or mechanical faults can create serious symptoms. Testing determines whether internal damage exists.", "We review scan data and history, inspect fluids and leaks, and use cooling, ignition, fuel, compression, timing, oil-pressure, or turbo tests where the evidence points."]),
  },
  {
    slug: "honda-check-engine-light-diagnostics-crown-point-in", shortName: "Honda Check-Engine-Light Diagnostics", kind: "service",
    title: "Honda Check Engine Light Crown Point | R Complete Auto Care",
    description: "Honda check-engine-light diagnosis in Crown Point using codes, freeze-frame and live data, circuit testing, smoke testing, compression testing, and verification.",
    eyebrow: "Codes are clues, not conclusions", heading: "Honda Check-Engine-Light Diagnostics",
    intro: "A diagnostic trouble code identifies a system, circuit, or operating condition. It does not automatically identify a failed part. We use the code as a path into testing and verify the cause before recommending replacement.",
    problems: ["Steady or flashing check-engine light", "Misfire, rough idle, stalling, or poor acceleration", "Fuel-trim, oxygen-sensor, catalyst, or evaporative-emissions faults", "Electrical circuit and communication faults", "Intermittent light with few obvious symptoms"],
    warningSigns: ["Flashing light", "Shaking or severe loss of power", "Overheating or oil-pressure warning", "Fuel smell or smoke", "Stalling in traffic"],
    diagnostic: "Depending on the fault, we use scan and freeze-frame data, live-data comparison, visual inspection, connector and circuit testing, smoke testing, fuel or ignition testing, compression testing, and a verification drive or monitor check.",
    services: ["Full-system scan and code documentation", "Freeze-frame and live-data analysis", "Circuit and connector testing", "Smoke testing where appropriate", "Misfire and compression testing", "Post-repair verification"],
    maintenance: "Warning lights are not maintenance reminders. Address them based on severity, symptoms, and diagnostic evidence; keeping basic engine maintenance current can also prevent avoidable drivability problems.",
    driving: "A steady light with normal operation may allow careful travel for diagnosis. A flashing light usually indicates an active misfire that can damage the catalytic converter; reduce load, stop safely, and call us.",
    timing: "Many faults can be narrowed down the same day. Intermittent electrical or evaporative faults may require extended testing or repeat conditions.",
    cost: "Diagnostic time depends on code complexity, accessibility, whether the symptom is present, and the testing needed. Repair cost follows the verified cause, not the code number alone.",
    warranty: "Diagnostic coverage varies by contract. If a covered component is responsible, we can provide findings to the extended warranty administrator.",
    related: ["honda-engine-repair-crown-point-in", "honda-civic-repair-crown-point-in", "honda-cr-v-repair-crown-point-in"],
    faqs: serviceFaqs("Check-Engine-Light Diagnostics", ["Does a Honda trouble code tell you which part to replace?", "No. A code identifies a detected system, circuit, or condition. Scan data and physical testing are needed to identify the cause.", "We capture codes, freeze-frame and live data, inspect the system, then perform circuit, smoke, fuel, ignition, compression, or other tests as appropriate before verifying the repair."]),
  },
  {
    slug: "honda-ac-repair-crown-point-in", shortName: "Honda A/C Repair", kind: "service",
    title: "Honda A/C Repair Crown Point, IN | R Complete Auto Care",
    description: "Honda A/C diagnostics in Crown Point for weak cooling, warm air, intermittent operation, leaks, electrical faults, condensers, compressors, and blend doors.",
    eyebrow: "Cooling-system diagnosis before parts", heading: "Honda A/C Repair and Diagnostics",
    intro: "Warm air does not automatically mean the compressor has failed. Refrigerant charge, leaks, electrical controls, sensors, fans, condenser airflow, blend doors, and mechanical components can produce similar symptoms.",
    problems: ["Weak or warm air", "Intermittent cooling", "Refrigerant leaks", "Compressor or clutch/control concerns", "Condenser damage or airflow problems", "Blend-door and temperature-control faults"],
    warningSigns: ["Cooling stops suddenly", "Unusual noise when A/C is selected", "Visible leakage or oily residue", "Engine temperature rises with A/C use", "Burning smell or repeated fuse failure"],
    diagnostic: "We confirm the complaint, measure vent temperature and system pressures where appropriate, inspect for leaks and condenser airflow, test electrical commands and power, and evaluate blend-door operation before identifying the failed component.",
    services: ["Performance and temperature testing", "Leak detection", "Electrical and control diagnosis", "Condenser and airflow inspection", "Compressor-system evaluation", "Blend-door and cabin-control diagnosis"],
    maintenance: "A/C service is condition- and vehicle-specific. Refrigerant type and charge procedure must match the exact Honda; adding refrigerant without finding a leak or measuring the system is not a complete diagnosis.",
    driving: "Most A/C faults do not prevent driving, but stop if there is a burning smell, belt problem, engine overheating, or another safety concern. Defrost performance also matters in humid or cold weather.",
    timing: "Performance testing may be quick, while small intermittent leaks or electrical faults can require more time. Repair time depends on component access and system service requirements.",
    cost: "Refrigerant type, leak location, electrical diagnosis, component access, required parts, and whether contamination or related damage is present affect cost.",
    warranty: "Some failed A/C components may be covered by an extended warranty, while refrigerant or leak-related exclusions vary. We can submit documentation for review.",
    related: ["honda-civic-repair-crown-point-in", "honda-accord-repair-crown-point-in", "honda-odyssey-repair-crown-point-in"],
    faqs: serviceFaqs("A/C Repair", ["Does warm air mean my Honda needs a compressor?", "No. Low refrigerant from a leak, electrical faults, fans, sensors, condenser airflow, blend doors, and other causes can all reduce cooling.", "We measure performance, inspect for leakage and airflow problems, evaluate pressures when appropriate, and test electrical commands and component operation before recommending parts."]),
  },
  {
    slug: "honda-brake-repair-crown-point-in", shortName: "Honda Brake Repair", kind: "service",
    title: "Honda Brake Repair Crown Point, IN | R Complete Auto Care",
    description: "Honda brake inspection and repair in Crown Point for pads, rotors, calipers, hoses, fluid, ABS warnings, vibration, noise, pulling, and pedal changes.",
    eyebrow: "Measured brake inspections", heading: "Honda Brake Repair and Diagnostics",
    intro: "Brake noise alone does not reveal the complete repair. We measure friction material and rotors, inspect caliper operation and hoses, evaluate fluid and pedal feel, and scan ABS concerns when warning lights are involved.",
    problems: ["Worn pads or rotors", "Sticking calipers or uneven wear", "Brake hoses or fluid concerns", "ABS or stability-control warning lights", "Vibration, noise, pulling, or pedal changes"],
    warningSigns: ["Grinding or metal-to-metal noise", "Soft, sinking, or unusually hard pedal", "Vehicle pulls sharply while braking", "Brake or ABS warning with changed braking behavior", "Fluid leakage or burning odor near a wheel"],
    diagnostic: "We road test when safe, measure pads and rotors, inspect calipers, slides, hoses, lines, and fluid condition, check for leaks, and scan ABS or stability systems when indicated.",
    services: ["Brake pad and rotor service", "Caliper and hardware repair", "Hose, line, and fluid inspection", "Brake-fluid service when appropriate", "ABS diagnosis", "Post-repair road test and verification"],
    maintenance: "Brake wear varies with driving, load, road conditions, corrosion, and component operation. Inspection measurements are more useful than a universal mileage interval.",
    driving: "Do not drive with grinding, fluid loss, a sinking pedal, severe pulling, or substantially reduced braking. Arrange safe transport and call us for guidance.",
    timing: "Routine brake service may be completed the same day when parts are available. ABS electrical diagnosis or seized and damaged components can extend the timeline.",
    cost: "Measured wear, rotor condition, caliper operation, corrosion, ABS diagnosis, parts quality, and damage from continued driving affect cost.",
    warranty: "Extended warranty coverage for brake systems varies and maintenance wear is often excluded. We can document a covered component failure for review.",
    related: ["honda-civic-repair-crown-point-in", "honda-hr-v-repair-crown-point-in", "honda-passport-repair-crown-point-in"],
    faqs: serviceFaqs("Brake Repair", ["Does brake noise always mean my Honda needs pads and rotors?", "No. Pads, rotors, hardware, shields, calipers, debris, and other conditions can create noise. Measurements and inspection determine the repair.", "We evaluate pedal feel and warning lights, measure pads and rotors, inspect calipers, hardware, hoses, fluid, and leaks, and scan ABS systems when needed."]),
  },
];

export const HONDA_PAGES = [...models, ...services];
export const HONDA_MODELS = models;
export const HONDA_SERVICES = services;

export function getHondaPage(slug: string): HondaPageData {
  const page = HONDA_PAGES.find((entry) => entry.slug === slug);
  if (!page) throw new Error(`Unknown Honda page: ${slug}`);
  return page;
}
