// Single source of truth for vehicle make ("<make>-repair-crown-point-in") pages.
// Content is written per make — genuine, brand-specific failure patterns we
// commonly diagnose, framed as "what we test for," never guaranteed defects.
// Customer-facing monetary specifics are prohibited here (see project conventions).

export const MAKE_BASE_URL = "https://www.rcompleteautocare.com";

export type MakeFaq = { question: string; answer: string };
export type MakeProblem = { name: string; detail: string };
export type MakeLink = { href: string; label: string };

export type MakePageData = {
  slug: string;
  make: string;
  title: string;
  description: string;
  eyebrow: string;
  heading: string;
  tldr: string;
  intro: string;
  problems: MakeProblem[];
  warningSigns: string[];
  diagnostic: string;
  services: string[];
  maintenance: string;
  driving: string;
  timing: string;
  cost: string;
  warranty: string;
  faqs: MakeFaq[];
  relatedServices: MakeLink[];
  relatedSymptoms: MakeLink[];
};

const makes: MakePageData[] = [
  {
    slug: "toyota-repair-crown-point-in",
    make: "Toyota",
    title: "Toyota Repair Crown Point IN | R Complete Auto Care",
    description: "Toyota and Lexus diagnostics and repair in Crown Point, IN — oil consumption, water pumps, VVT-i, hybrid systems, and D-4S carbon. (219) 262-2711.",
    eyebrow: "Independent Toyota service in Crown Point",
    heading: "Toyota Repair and Diagnostics in Crown Point, IN",
    tldr: "R Complete Auto Care diagnoses and repairs Toyota cars, trucks, and hybrids at our Crown Point, IN shop. We test the actual system before recommending parts, handle extended-warranty claims, and serve Crown Point, St. John, Schererville, Merrillville, and Cedar Lake.",
    intro: "Toyota vehicles earn their reputation for longevity, but even a well-built Camry, Corolla, RAV4, Tacoma, Highlander, or Prius benefits from diagnosis rather than assumptions once a warning light, noise, or fluid concern appears. We identify the exact engine, drivetrain, and hybrid configuration before testing the system a customer describes.",
    problems: [
      { name: "Oil consumption on some 2AZ-FE four-cylinders", detail: "Certain 2007-2011 Camry, RAV4, and Scion engines can burn oil as piston rings and oil-control components wear. We measure consumption over distance, inspect for leaks versus combustion, and confirm the cause before recommending a repair rather than assuming the worst." },
      { name: "Water pump and cooling-system leaks", detail: "Water pumps, radiators, and plastic cooling components age on high-mileage Toyota engines. Because overheating can damage a head gasket, we pressure-test the cooling system and pinpoint the leak instead of topping off coolant and waiting." },
      { name: "VVT-i variable valve timing concerns", detail: "A rough idle, oil-pressure code, or timing rattle can trace to VVT-i actuators, oil-control valves, or a stretched timing chain on some engines. We compare scan data and oil condition before condemning a component." },
      { name: "Hybrid system and HV battery aging", detail: "On Prius and other Toyota hybrids, an aging high-voltage battery, inverter coolant pump, or hybrid warning can mimic engine trouble. We read the hybrid modules and test the traction battery before recommending expensive assemblies." },
      { name: "D-4S direct-injection carbon buildup", detail: "Direct-injected Toyota and Lexus engines can accumulate intake-valve carbon that causes misfires or rough running. We verify the condition through data and inspection rather than assuming every misfire needs the same fix." },
    ],
    warningSigns: [
      "Oil level dropping between changes with no visible leak",
      "Temperature gauge climbing or coolant loss",
      "Hybrid warning light or reduced electric-mode operation",
      "Rough idle, misfire, or a timing-area rattle at cold start",
      "Repeated low-oil or check-engine warnings",
    ],
    diagnostic: "We start with the model, engine, mileage, and service history, then road test when it is safe. Depending on the concern, testing can include scan and freeze-frame data, a cooling-system pressure test, an oil-consumption measurement, hybrid module scans and traction-battery evaluation, or intake inspection for carbon.",
    services: [
      "Engine and oil-consumption diagnosis",
      "Cooling-system and water-pump repair",
      "VVT-i and timing diagnosis",
      "Hybrid system and HV battery testing",
      "Check-engine-light and emissions diagnosis",
      "Brake, suspension, and maintenance service",
    ],
    maintenance: "Toyota service needs vary by engine, hybrid or conventional drivetrain, mileage, and how the vehicle is driven. We use the owner's manual and vehicle-specific information — including the correct pink Toyota coolant and hybrid-specific procedures — rather than a one-size interval.",
    driving: "A steady warning light with normal operation may allow a careful trip for diagnosis, but overheating, an oil-pressure light, a flashing check-engine light, or a hybrid-system warning means stop and call us.",
    timing: "Straightforward inspections are often same-day. Intermittent hybrid, cooling, or oil-consumption concerns can require added testing, and repair time then depends on parts availability and access.",
    cost: "Cost depends on the engine and whether the vehicle is hybrid, the diagnostic time, parts access, and whether one failure has affected another system. Diagnosis comes first so the estimate matches the demonstrated fault.",
    warranty: "Many Toyota engine, cooling, and hybrid repairs are commonly covered by extended service contracts. We document the diagnosis and work with administrators such as CarShield, Endurance, and CARS Protection Plus while your contract governs coverage.",
    faqs: [
      { question: "Do you repair Toyota vehicles in Crown Point?", answer: "Yes. R Complete Auto Care diagnoses and repairs Toyota cars, trucks, SUVs, and hybrids — including Camry, Corolla, RAV4, Tacoma, Highlander, and Prius — at our Crown Point, IN shop." },
      { question: "Can you service a Toyota or Prius hybrid?", answer: "Yes. We scan the hybrid modules, evaluate the high-voltage battery and inverter cooling, and diagnose hybrid warnings. We tell you what the system is actually reporting before recommending any high-voltage component." },
      { question: "My Toyota is burning oil — does it need an engine?", answer: "Not necessarily. Oil use can come from rings, valve seals, PCV issues, or external leaks. We measure consumption and inspect the engine before assuming an internal repair is required." },
      { question: "Do you handle Toyota extended warranty claims?", answer: "Yes. We document findings, contact your warranty administrator, and respond to their requests. The contract's terms decide coverage and authorization." },
      { question: "Can you diagnose my Toyota the same day?", answer: "Many Toyota diagnostics are completed the same day. Call (219) 262-2711 with the model, mileage, and symptoms so we can prepare for your visit." },
    ],
    relatedServices: [
      { href: "/services/engine-repair", label: "Engine repair" },
      { href: "/services/check-engine-light", label: "Check engine light diagnostics" },
      { href: "/services/ac-heating-repair", label: "A/C and heating repair" },
      { href: "/services/oil-change-maintenance", label: "Oil change and maintenance" },
    ],
    relatedSymptoms: [
      { href: "/car-overheating-crown-point-in", label: "Car overheating help" },
      { href: "/check-engine-light-flashing-crown-point", label: "Flashing check engine light" },
    ],
  },
  {
    slug: "chevrolet-repair-crown-point-in",
    make: "Chevrolet",
    title: "Chevrolet Repair Crown Point IN | R Complete Auto Care",
    description: "Chevy diagnostics and repair in Crown Point, IN — AFM/DFM lifter failure, 8-speed shudder, timing chains, and oil consumption. (219) 262-2711.",
    eyebrow: "Independent Chevrolet service in Crown Point",
    heading: "Chevrolet Repair and Diagnostics in Crown Point, IN",
    tldr: "R Complete Auto Care diagnoses and repairs Chevrolet cars, trucks, and SUVs in Crown Point, IN — from Silverado and Equinox to Malibu and Traverse. We test before we replace, handle extended-warranty claims, and serve all of Northwest Indiana.",
    intro: "Chevrolet builds everything from the Silverado and Tahoe to the Equinox, Malibu, and Traverse, and each platform has its own known concerns. We confirm the engine and transmission before testing, because a lifter tick, a shudder, or a coolant smell each points to a different investigation.",
    problems: [
      { name: "AFM/DFM lifter failure on 5.3L and 6.2L V8s", detail: "Active Fuel Management and Dynamic Fuel Management lifters can collapse on Silverado, Tahoe, and Suburban V8s, causing a tick, misfire, or dead cylinder. We confirm the failed cylinder with data and mechanical testing before recommending lifter and camshaft work." },
      { name: "8-speed (8L90/8L45) transmission shudder", detail: "The 8-speed automatic in many trucks and SUVs can shudder or shift harshly, often tied to fluid condition and valve-body wear. We road test, inspect the fluid using the correct procedure, and scan before recommending a fluid service or repair." },
      { name: "3.6L V6 timing chain and cooling concerns", detail: "Timing-chain stretch, water-pump leaks, and intake gaskets appear on some 3.6L Traverse, Equinox, Camaro, and Malibu engines. A stretched chain sets timing codes, so we verify with scan data before major work." },
      { name: "Oil consumption and PCV issues", detail: "Some Chevrolet engines consume oil through rings or a failing PCV system. We measure consumption and inspect the crankcase ventilation before assuming the engine needs internal repair." },
      { name: "Turbo and coolant concerns on Cruze and Malibu", detail: "The 1.4L turbo can develop coolant leaks, PCV diaphragm failure, and boost concerns. We pressure-test the cooling system and check the intake for the real cause of a low-coolant or check-engine complaint." },
    ],
    warningSigns: [
      "Lifter tick, misfire, or a cylinder dropping out",
      "Shudder or harsh shifts from the automatic transmission",
      "Coolant loss, sweet smell, or overheating",
      "Oil level dropping with no obvious leak",
      "Reduced power or a flashing check-engine light",
    ],
    diagnostic: "We identify the exact engine and transmission, review the customer's description and history, and road test when safe. Testing may include scan and misfire data, a cooling-system pressure test, fuel-trim analysis, transmission road testing with fluid inspection, or mechanical verification of a suspected lifter or timing concern.",
    services: [
      "V8 lifter and camshaft diagnosis",
      "Automatic-transmission diagnosis and service",
      "Timing-chain and cooling-system repair",
      "Oil-consumption and PCV diagnosis",
      "Turbo-system and boost diagnosis",
      "Brake, suspension, and electrical service",
    ],
    maintenance: "Chevrolet maintenance varies by engine, transmission, and truck-versus-car duty. Oil specification, transmission-fluid service, and cooling-system intervals should follow the owner's manual and vehicle-specific information, not a generic schedule.",
    driving: "Stop and call for overheating, an oil-pressure warning, a flashing check-engine light, a severe misfire, or a transmission that slips into traffic. Milder symptoms still deserve timely inspection before they worsen.",
    timing: "A visible leak or wear item may be diagnosed the same day. Lifter, timing, or intermittent transmission concerns can take more testing, and repair time then depends on access and parts.",
    cost: "The estimate reflects the engine and transmission, diagnostic depth, parts access, and whether one failure has caused another. We test first so a lifter tick is not treated like a simple tune-up when it is not.",
    warranty: "AFM lifter, timing, and transmission repairs are frequently covered by extended service contracts. We document the failure and coordinate with providers like CarShield, Endurance, and AmTrust while your contract decides coverage.",
    faqs: [
      { question: "Do you repair Chevrolet vehicles in Crown Point?", answer: "Yes. We diagnose and repair Chevrolet cars, trucks, and SUVs — Silverado, Equinox, Malibu, Traverse, Tahoe, Camaro, and more — at our Crown Point, IN shop." },
      { question: "My Chevy V8 has a lifter tick — what causes it?", answer: "On 5.3L and 6.2L engines, AFM/DFM lifters can collapse and cause a tick or misfire. We confirm the affected cylinder with scan data and mechanical testing before recommending lifter and camshaft repair." },
      { question: "Why does my Chevy 8-speed shudder?", answer: "The 8L90/8L45 automatic can shudder from fluid condition or valve-body wear. We road test and inspect the fluid with the correct procedure before recommending a service or repair." },
      { question: "Do you handle Chevrolet extended warranty claims?", answer: "Yes. We document the diagnosis and work with your warranty administrator on covered engine and transmission repairs. Coverage and authorization follow your contract." },
      { question: "Can you diagnose my Chevrolet the same day?", answer: "Many Chevrolet diagnostics finish the same day. Call (219) 262-2711 with the model, engine, and symptoms so we can prepare." },
    ],
    relatedServices: [
      { href: "/services/engine-repair", label: "Engine repair" },
      { href: "/services/transmission-repair", label: "Transmission repair" },
      { href: "/services/check-engine-light", label: "Check engine light diagnostics" },
      { href: "/services/diagnostics", label: "Auto diagnostics" },
    ],
    relatedSymptoms: [
      { href: "/transmission-slipping-crown-point-in", label: "Transmission slipping help" },
      { href: "/car-overheating-crown-point-in", label: "Car overheating help" },
    ],
  },
  {
    slug: "ford-repair-crown-point-in",
    make: "Ford",
    title: "Ford Repair Crown Point IN | R Complete Auto Care",
    description: "Ford diagnostics and repair in Crown Point, IN — cam phaser rattle, internal water pumps, EcoBoost turbo, and PowerShift shudder. (219) 262-2711.",
    eyebrow: "Independent Ford service in Crown Point",
    heading: "Ford Repair and Diagnostics in Crown Point, IN",
    tldr: "R Complete Auto Care diagnoses and repairs Ford cars, trucks, and SUVs in Crown Point, IN — F-150, Explorer, Escape, Edge, Fusion, and more. We test the actual system before recommending parts and handle extended-warranty claims across Northwest Indiana.",
    intro: "From the F-150 and Explorer to the Escape, Edge, and Fusion, Ford platforms each carry their own known patterns. We identify the exact engine — Ti-VCT, EcoBoost, or a heavy-duty Super Duty diesel — before we test, because a cold-start rattle, a coolant loss, or a shudder each leads a different direction.",
    problems: [
      { name: "Cam phaser rattle on 3.5L and 5.0L Ti-VCT engines", detail: "A cold-start rattle from variable-cam-timing phasers is common on some F-150 and Mustang engines. We verify with scan data and inspection because a phaser, oil-control valve, or oil-supply issue can each produce the noise." },
      { name: "Internal water pump on 3.5L/3.7L Duratec V6s", detail: "Some Duratec V6 engines route the water pump inside the timing cover, so a failing pump can leak coolant into the oil. We confirm the leak path before recommending this timing-cover-access repair." },
      { name: "EcoBoost turbo, carbon, and coolant concerns", detail: "Direct-injected EcoBoost engines can develop intake-valve carbon, turbo or wastegate faults, and coolant intrusion on certain 1.5L/1.6L engines. We test boost, fuel trims, and the cooling system before condemning a turbo." },
      { name: "PowerShift dual-clutch shudder (Fiesta/Focus)", detail: "The dry dual-clutch automatic in some 2011-2018 Fiesta and Focus models can shudder, hesitate, or set clutch codes. We scan the transmission control module and evaluate clutch and input-shaft data before recommending work." },
      { name: "Super Duty and truck-specific concerns", detail: "Death wobble, exhaust manifold studs, and diesel injection or emissions faults appear on heavier Ford trucks. We inspect steering and driveline components and scan the powertrain before recommending a repair path." },
    ],
    warningSigns: [
      "Cold-start rattle that fades after a few seconds",
      "Coolant loss with milky oil or overheating",
      "Turbo whistle, loss of power, or a boost code",
      "Shuddering or hesitation from an automatic transmission",
      "Steering wobble or a vibration through the wheel",
    ],
    diagnostic: "We confirm the engine and transmission, review history, and road test when safe. Testing can include scan and freeze-frame data, timing and phaser evaluation, a cooling-system pressure test, boost and fuel-trim analysis, transmission control-module data, or steering and driveline inspection for wobble complaints.",
    services: [
      "Cam phaser and timing diagnosis",
      "Cooling-system and internal water-pump repair",
      "EcoBoost turbo and carbon diagnosis",
      "Automatic and dual-clutch transmission diagnosis",
      "Steering, suspension, and driveline service",
      "Check-engine-light and electrical diagnosis",
    ],
    maintenance: "Ford maintenance depends on the engine, whether it is turbocharged or diesel, and truck-versus-car use. Oil specification, spark-plug intervals, and cooling service should follow the owner's manual and vehicle-specific guidance.",
    driving: "Stop for overheating, milky oil, an oil-pressure warning, a flashing check-engine light, or a severe steering wobble. A faint cold-start rattle should still be inspected before it progresses.",
    timing: "A visible leak or wear item may be same-day. Cam-phaser, internal-water-pump, or intermittent transmission diagnosis can take longer, and repair time depends on access and parts.",
    cost: "The estimate depends on the engine, whether the repair requires timing-cover access, diagnostic time, and parts. We test first so a rattle is not treated as a phaser job before the source is confirmed.",
    warranty: "Cam-phaser, water-pump, turbo, and transmission repairs are frequently covered by extended service contracts. We document the diagnosis and coordinate with providers such as Endurance, CarShield, and SilverRock while your contract governs coverage.",
    faqs: [
      { question: "Do you repair Ford vehicles in Crown Point?", answer: "Yes. We diagnose and repair Ford cars, trucks, and SUVs — F-150, Explorer, Escape, Edge, Fusion, and more — at our Crown Point, IN shop." },
      { question: "What causes the cold-start rattle on my Ford?", answer: "On 3.5L and 5.0L Ti-VCT engines the rattle often traces to cam phasers, but the oil-control valves and oil supply can contribute. We test before recommending phaser replacement." },
      { question: "Why is coolant getting into my Ford's oil?", answer: "Some Duratec V6 engines use an internal water pump inside the timing cover; a failed pump can leak coolant into the oil. We confirm the source before recommending the repair." },
      { question: "Do you handle Ford extended warranty claims?", answer: "Yes. We document the diagnosis and work with your warranty administrator on covered repairs. Coverage and authorization depend on your contract." },
      { question: "Can you diagnose my Ford the same day?", answer: "Many Ford diagnostics finish the same day. Call (219) 262-2711 with the model, engine, and symptoms so we can prepare." },
    ],
    relatedServices: [
      { href: "/services/engine-repair", label: "Engine repair" },
      { href: "/services/transmission-repair", label: "Transmission repair" },
      { href: "/services/suspension-steering", label: "Suspension and steering" },
      { href: "/services/check-engine-light", label: "Check engine light diagnostics" },
    ],
    relatedSymptoms: [
      { href: "/car-overheating-crown-point-in", label: "Car overheating help" },
      { href: "/transmission-slipping-crown-point-in", label: "Transmission slipping help" },
    ],
  },
  {
    slug: "nissan-repair-crown-point-in",
    make: "Nissan",
    title: "Nissan Repair Crown Point IN | R Complete Auto Care",
    description: "Nissan diagnostics and repair in Crown Point, IN — CVT judder and overheating, timing-chain rattle, and catalytic concerns. (219) 262-2711.",
    eyebrow: "Independent Nissan service in Crown Point",
    heading: "Nissan Repair and Diagnostics in Crown Point, IN",
    tldr: "R Complete Auto Care diagnoses and repairs Nissan cars and SUVs in Crown Point, IN — Altima, Rogue, Sentra, Pathfinder, and more. We focus on CVT diagnosis done right, handle extended-warranty claims, and serve all of Northwest Indiana.",
    intro: "Nissan's Altima, Rogue, Sentra, Murano, and Pathfinder are common on Crown Point roads, and many share the Xtronic CVT that requires careful, specific diagnosis. We identify the exact transmission and engine before testing, because a shudder or a whine is not always what it first appears.",
    problems: [
      { name: "Xtronic CVT judder, overheating, and failure", detail: "Nissan's continuously variable transmission can shudder, whine, hesitate, or overheat on Altima, Rogue, Sentra, and Murano. We confirm the transmission type, inspect fluid condition with the correct procedure, road test, and scan before recommending service or replacement." },
      { name: "Timing-chain rattle on QR and MR engines", detail: "A cold-start timing-chain rattle can develop on some 2.5L QR25 and related engines as the chain, tensioner, or guides wear. We verify with scan data and inspection before recommending timing work." },
      { name: "Catalytic converter and emissions faults", detail: "Some Nissan engines set catalyst-efficiency or fuel-trim codes that can trace to the converter, sensors, or an upstream cause. We test fuel trims and oxygen-sensor data before condemning a converter." },
      { name: "CVT cooling and fluid-service concerns", detail: "Because CVT overheating accelerates wear, cooler flow and fluid condition matter. We evaluate the cooling path and fluid, and we are clear that a fluid service is maintenance, not a guaranteed repair for an existing internal fault." },
      { name: "Electrical, fuel-level, and A/C concerns", detail: "Fuel-level sensor faults, A/C performance, and battery or charging issues also appear across the Nissan lineup. We test the specific circuit or system rather than replacing parts by guess." },
    ],
    warningSigns: [
      "Shudder, whine, or hesitation from the transmission",
      "Burning smell or a transmission overheat warning",
      "Cold-start rattle from the timing-chain area",
      "Check-engine light with a catalyst or fuel-trim code",
      "Loss of acceleration or the vehicle slipping out of gear",
    ],
    diagnostic: "We confirm the transmission and engine, review history, and road test when safe. CVT diagnosis includes fluid inspection using the correct method, scan and live data, cooler-flow evaluation, and mechanical checks; engine concerns add timing, fuel-trim, and emissions testing as the evidence requires.",
    services: [
      "Xtronic CVT diagnosis and service",
      "Timing-chain and engine diagnosis",
      "Catalytic and emissions diagnosis",
      "Cooling and fluid-service evaluation",
      "Electrical and A/C diagnosis",
      "Brake, suspension, and maintenance service",
    ],
    maintenance: "Nissan maintenance depends on the engine and whether the vehicle uses a CVT or conventional automatic. CVT fluid type and service intervals are specific; we follow the owner's manual and vehicle-specific information rather than a universal schedule.",
    driving: "Continued driving with a severe CVT shudder, slipping, overheating, or loss of drive can be unsafe and may worsen damage. Stop and call for guidance; milder symptoms still deserve prompt testing.",
    timing: "Road testing and scan diagnosis can be prompt, while intermittent CVT or emissions faults can take longer. Major transmission timing depends on the confirmed plan and parts availability.",
    cost: "The estimate reflects the transmission type, diagnostic time, whether the cause is electrical or internal, and parts access. Testing prevents a fluid service from being mistaken for a repair of an internal failure.",
    warranty: "CVT and engine repairs are commonly covered by extended service contracts. We document the diagnosis and work with administrators such as CarShield, Endurance, and CARS Protection Plus while your contract decides coverage.",
    faqs: [
      { question: "Do you repair Nissan vehicles in Crown Point?", answer: "Yes. We diagnose and repair Nissan cars and SUVs — Altima, Rogue, Sentra, Murano, Pathfinder, and more — at our Crown Point, IN shop." },
      { question: "Can you diagnose a Nissan CVT problem?", answer: "Yes. We confirm the transmission type, inspect the fluid with the correct procedure, road test, and scan before recommending a service or replacement. We do not guess at a CVT." },
      { question: "Will a CVT fluid service fix my Nissan's shudder?", answer: "Not necessarily. A fluid service can be appropriate maintenance, but internal wear, overheating damage, or control faults require diagnosis and are not repaired by fluid alone." },
      { question: "Do you handle Nissan extended warranty claims?", answer: "Yes. We document findings and coordinate with your warranty administrator on covered repairs. Coverage and authorization follow your contract." },
      { question: "Can you diagnose my Nissan the same day?", answer: "Many Nissan diagnostics finish the same day. Call (219) 262-2711 with the model and symptoms so we can prepare." },
    ],
    relatedServices: [
      { href: "/services/transmission-repair", label: "Transmission repair" },
      { href: "/services/engine-repair", label: "Engine repair" },
      { href: "/services/check-engine-light", label: "Check engine light diagnostics" },
      { href: "/services/diagnostics", label: "Auto diagnostics" },
    ],
    relatedSymptoms: [
      { href: "/transmission-slipping-crown-point-in", label: "Transmission slipping help" },
      { href: "/check-engine-light-flashing-crown-point", label: "Flashing check engine light" },
    ],
  },
  {
    slug: "subaru-repair-crown-point-in",
    make: "Subaru",
    title: "Subaru Repair Crown Point IN | R Complete Auto Care",
    description: "Subaru diagnostics and repair in Crown Point, IN — head gaskets, oil consumption, CVT, wheel bearings, and AWD service. (219) 262-2711.",
    eyebrow: "Independent Subaru service in Crown Point",
    heading: "Subaru Repair and Diagnostics in Crown Point, IN",
    tldr: "R Complete Auto Care diagnoses and repairs Subaru cars and SUVs in Crown Point, IN — Outback, Forester, Impreza, Crosstrek, and Legacy. We know boxer-engine and AWD patterns, handle extended-warranty claims, and serve all of Northwest Indiana.",
    intro: "Subaru's boxer engines and standard all-wheel drive are well suited to Indiana winters, but they bring their own service patterns. We confirm the exact engine and whether the vehicle uses a CVT before testing, because oil use, a coolant smell, or a drivetrain vibration each require a different approach.",
    problems: [
      { name: "Head-gasket leaks on EJ-series boxer engines", detail: "Older 2.5L EJ25 engines are known for external head-gasket leaks of oil or coolant. We pressure-test the cooling system, inspect for combustion gases, and confirm the leak before recommending this labor-intensive repair." },
      { name: "Oil consumption on FB-series engines", detail: "Some 2011-2015 FB25 engines can consume oil through piston-ring wear. We measure consumption over distance and inspect the engine before assuming an internal repair is needed." },
      { name: "CVT (Lineartronic) behavior and service", detail: "Subaru's CVT can develop shudder, hesitation, or warning messages. We confirm the transmission, inspect fluid, road test, and scan before recommending service, and we distinguish maintenance from repair of an internal fault." },
      { name: "Wheel bearings and AWD driveline noise", detail: "A hum or growl that changes with speed or cornering can be a wheel bearing, while a bind or vibration can be AWD-related. We isolate the source with a road test and inspection instead of replacing parts by guess." },
      { name: "Timing components and oil leaks", detail: "Timing belts or chains, cam and crank seals, and oil-separator leaks appear as engines age. We inspect for the leak source and review service history before defining the scope." },
    ],
    warningSigns: [
      "Coolant loss, oil seepage, or a sweet smell after driving",
      "Oil level dropping between changes",
      "Shudder or hesitation from the CVT",
      "Humming or growling that changes with speed or turns",
      "Overheating or a temperature gauge climbing",
    ],
    diagnostic: "We confirm the engine and transmission, review history, and road test when safe. Testing can include a cooling-system pressure test and combustion-gas check, an oil-consumption measurement, CVT fluid inspection and road testing, and wheel-bearing or AWD isolation for noise and vibration complaints.",
    services: [
      "Head-gasket and cooling-system diagnosis",
      "Oil-consumption and engine diagnosis",
      "CVT diagnosis and service",
      "Wheel-bearing and AWD driveline service",
      "Timing and oil-leak repair",
      "Brake, suspension, and maintenance service",
    ],
    maintenance: "Subaru maintenance depends on the engine, whether it uses a timing belt or chain, and CVT service needs. We follow the owner's manual and vehicle-specific information — including AWD tire-matching guidance that protects the drivetrain — rather than a generic schedule.",
    driving: "Stop for overheating, an oil-pressure warning, or a severe drivetrain vibration. A minor coolant seep or oil use still deserves inspection before it becomes a larger repair.",
    timing: "A visible leak or wear item may be diagnosed the same day. Head-gasket, CVT, or intermittent driveline concerns can take more testing, and repair time depends on access and parts.",
    cost: "The estimate reflects the engine, whether boxer-engine access is required, diagnostic time, and parts. AWD and CVT configurations influence the plan, so we confirm the cause before quoting.",
    warranty: "Head-gasket, engine, and CVT repairs are frequently covered by extended service contracts. We document the diagnosis and coordinate with providers like Endurance, CarShield, and AmTrust while your contract governs coverage.",
    faqs: [
      { question: "Do you repair Subaru vehicles in Crown Point?", answer: "Yes. We diagnose and repair Subaru cars and SUVs — Outback, Forester, Impreza, Crosstrek, and Legacy — at our Crown Point, IN shop, including boxer-engine and AWD service." },
      { question: "Is my Subaru's coolant smell a head gasket?", answer: "It can be, especially on older EJ25 engines, but it can also be a hose, water pump, or other leak. We pressure-test and inspect before recommending a head-gasket repair." },
      { question: "Why does my Subaru use oil?", answer: "Some FB-series engines consume oil through ring wear, and leaks or PCV issues also contribute. We measure consumption and inspect before assuming internal repair." },
      { question: "Do you handle Subaru extended warranty claims?", answer: "Yes. We document findings and work with your warranty administrator on covered engine, gasket, and CVT repairs. Coverage follows your contract." },
      { question: "Can you diagnose my Subaru the same day?", answer: "Many Subaru diagnostics finish the same day. Call (219) 262-2711 with the model and symptoms so we can prepare." },
    ],
    relatedServices: [
      { href: "/services/engine-repair", label: "Engine repair" },
      { href: "/services/transmission-repair", label: "Transmission repair" },
      { href: "/services/suspension-steering", label: "Suspension and steering" },
      { href: "/services/oil-change-maintenance", label: "Oil change and maintenance" },
    ],
    relatedSymptoms: [
      { href: "/car-overheating-crown-point-in", label: "Car overheating help" },
      { href: "/transmission-slipping-crown-point-in", label: "Transmission slipping help" },
    ],
  },
  {
    slug: "jeep-repair-crown-point-in",
    make: "Jeep",
    title: "Jeep Repair Crown Point IN | R Complete Auto Care",
    description: "Jeep diagnostics and repair in Crown Point, IN — 3.6 Pentastar heads, death wobble, oil filter housing leaks, and electrical. (219) 262-2711.",
    eyebrow: "Independent Jeep service in Crown Point",
    heading: "Jeep Repair and Diagnostics in Crown Point, IN",
    tldr: "R Complete Auto Care diagnoses and repairs Jeep vehicles in Crown Point, IN — Grand Cherokee, Wrangler, Cherokee, and Compass. We know Pentastar and solid-axle patterns, handle extended-warranty claims, and serve all of Northwest Indiana.",
    intro: "Jeep's Grand Cherokee, Wrangler, Cherokee, and Compass mix on-road comfort with off-road hardware, and each brings distinct concerns. We confirm the engine and drivetrain before testing, because a misfire, a steering wobble, or an oil leak each points to a different system.",
    problems: [
      { name: "3.6L Pentastar cylinder-head and misfire concerns", detail: "Some early 3.6L Pentastar engines developed left-bank cylinder-head issues causing misfires and ticking, while later concerns include rocker arms and lifters. We confirm the failed cylinder and mechanism with scan and mechanical data before recommending head or valvetrain work." },
      { name: "Death wobble on solid-front-axle Wranglers", detail: "A violent steering shake after hitting a bump can trace to worn track bars, ball joints, steering dampers, or tie rods. We inspect and measure the steering and suspension components to find the real cause rather than replacing one part and hoping." },
      { name: "Oil filter housing and cooler leaks", detail: "The plastic oil-filter housing on 3.6L engines can crack and leak oil or coolant. We confirm the leak source before recommending the housing or cooler repair." },
      { name: "TIPM and electrical faults", detail: "The Totally Integrated Power Module and related wiring can cause no-start, stalling, or accessory faults on some Grand Cherokee and other models. We test the circuit and module behavior before condemning expensive electronics." },
      { name: "Transmission and water-pump concerns", detail: "The 8-speed automatic, water pumps, and cooling components also need attention as these vehicles age. We road test and pressure-test to separate a control fault from a mechanical one." },
    ],
    warningSigns: [
      "Misfire, tick, or a flashing check-engine light",
      "Violent steering shake after hitting a bump",
      "Oil or coolant leak near the filter housing",
      "No-start, stalling, or accessory electrical faults",
      "Overheating or a transmission shifting harshly",
    ],
    diagnostic: "We confirm the engine and drivetrain, review history, and road test when safe. Testing can include scan and misfire data, mechanical valvetrain checks, a steering and suspension inspection for wobble, cooling-system pressure testing, and electrical circuit or module testing for no-start and accessory faults.",
    services: [
      "Pentastar cylinder-head and misfire diagnosis",
      "Steering, track-bar, and death-wobble diagnosis",
      "Oil-filter-housing and cooling-system repair",
      "TIPM and electrical diagnosis",
      "Transmission diagnosis and service",
      "Brake, suspension, and maintenance service",
    ],
    maintenance: "Jeep maintenance depends on the engine, drivetrain, and whether the vehicle sees off-road or towing duty. Fluid, driveline, and cooling service should follow the owner's manual and vehicle-specific severe-use guidance where it applies.",
    driving: "Stop for a flashing check-engine light, overheating, an oil-pressure warning, or a death-wobble event that makes the vehicle hard to control. Have new steering or driveline symptoms checked before highway driving.",
    timing: "A visible leak or steering-component check may be same-day. Cylinder-head, electrical, or intermittent concerns can take more testing, and repair time depends on access and parts.",
    cost: "The estimate reflects the engine and drivetrain, diagnostic time, and parts. Steering-wobble diagnosis in particular saves money by identifying the worn component instead of replacing several at once.",
    warranty: "Pentastar head, electrical, and transmission repairs are frequently covered by extended service contracts. We document the diagnosis and coordinate with providers like CarShield, Endurance, and CARS Protection Plus while your contract governs coverage.",
    faqs: [
      { question: "Do you repair Jeep vehicles in Crown Point?", answer: "Yes. We diagnose and repair Jeep vehicles — Grand Cherokee, Wrangler, Cherokee, and Compass — at our Crown Point, IN shop." },
      { question: "What causes Jeep death wobble?", answer: "It is usually worn steering or suspension components — track bar, ball joints, steering damper, or tie rods — often triggered by a bump. We inspect and measure to find the actual cause before replacing parts." },
      { question: "Why is my Jeep 3.6 misfiring?", answer: "Some early Pentastar engines had cylinder-head issues, and later concerns include rocker arms and lifters. We confirm the cylinder and mechanism with data before recommending repair." },
      { question: "Do you handle Jeep extended warranty claims?", answer: "Yes. We document findings and work with your warranty administrator on covered repairs. Coverage and authorization follow your contract." },
      { question: "Can you diagnose my Jeep the same day?", answer: "Many Jeep diagnostics finish the same day. Call (219) 262-2711 with the model, engine, and symptoms so we can prepare." },
    ],
    relatedServices: [
      { href: "/services/engine-repair", label: "Engine repair" },
      { href: "/services/suspension-steering", label: "Suspension and steering" },
      { href: "/services/electrical-diagnostics", label: "Electrical diagnostics" },
      { href: "/services/check-engine-light", label: "Check engine light diagnostics" },
    ],
    relatedSymptoms: [
      { href: "/car-wont-start-crown-point-in", label: "Car won't start help" },
      { href: "/check-engine-light-flashing-crown-point", label: "Flashing check engine light" },
    ],
  },
  {
    slug: "chrysler-repair-crown-point-in",
    make: "Chrysler",
    title: "Chrysler Repair Crown Point IN | R Complete Auto Care",
    description: "Chrysler diagnostics and repair in Crown Point, IN — 3.6 Pentastar, Pacifica, Tigershark oil use, TIPM electrical, and A/C. (219) 262-2711.",
    eyebrow: "Independent Chrysler service in Crown Point",
    heading: "Chrysler Repair and Diagnostics in Crown Point, IN",
    tldr: "R Complete Auto Care diagnoses and repairs Chrysler vehicles in Crown Point, IN — Pacifica, 300, and Town & Country. We know Pentastar and minivan patterns, handle extended-warranty claims, and serve all of Northwest Indiana.",
    intro: "Chrysler's Pacifica, 300, and Town & Country cover family hauling and full-size comfort, and each has distinct service patterns. We confirm the engine and configuration before testing, because a misfire, an electrical fault, or a transmission concern each requires its own investigation.",
    problems: [
      { name: "3.6L Pentastar misfire and valvetrain concerns", detail: "The 3.6L in the 300 and Pacifica can develop misfires from cylinder-head issues on early engines or rocker-arm and lifter wear later. We confirm the cylinder and mechanism with scan and mechanical data before recommending repair." },
      { name: "Pacifica electrical and hybrid concerns", detail: "The Pacifica, including the plug-in hybrid, can present electrical, charging, or warning-light faults. We scan the relevant modules and test the circuit before condemning a component or high-voltage assembly." },
      { name: "Tigershark 2.4L oil consumption", detail: "Some four-cylinder Chrysler applications can consume oil and set low-oil or check-engine warnings. We measure consumption and inspect the engine and PCV system before assuming internal repair." },
      { name: "TIPM and power-distribution faults", detail: "The Totally Integrated Power Module and wiring can cause no-start, stalling, or accessory faults. We test the module behavior and circuits before recommending expensive electronics." },
      { name: "62TE transmission and A/C concerns", detail: "The front-drive automatic and the climate system also need attention as these vehicles age. We road test, inspect fluid, and measure A/C performance before recommending work." },
    ],
    warningSigns: [
      "Misfire, rough running, or a flashing check-engine light",
      "No-start, stalling, or accessory electrical faults",
      "Oil level dropping with low-oil warnings",
      "Harsh shifting or slipping from the transmission",
      "Weak A/C cooling or a charging-system warning",
    ],
    diagnostic: "We confirm the engine and configuration, review history, and road test when safe. Testing can include scan and misfire data, mechanical valvetrain checks, electrical circuit and module testing, transmission road testing with fluid inspection, and A/C performance and pressure evaluation.",
    services: [
      "Pentastar misfire and valvetrain diagnosis",
      "Electrical and TIPM diagnosis",
      "Oil-consumption and engine diagnosis",
      "Transmission diagnosis and service",
      "A/C and heating repair",
      "Brake, suspension, and maintenance service",
    ],
    maintenance: "Chrysler maintenance depends on the engine, transmission, and whether the vehicle is a hybrid. Fluid, cooling, and service intervals should follow the owner's manual and vehicle-specific information rather than a generic schedule.",
    driving: "Stop for a flashing check-engine light, overheating, an oil-pressure warning, or stalling in traffic. Electrical or A/C faults may allow driving but should be assessed before daily reliance.",
    timing: "A visible concern may be same-day. Electrical, valvetrain, or intermittent faults can require more testing, and repair time depends on access and parts.",
    cost: "The estimate reflects the engine, whether the concern is electrical or mechanical, diagnostic time, and parts. Testing prevents replacing electronics or valvetrain parts before the cause is confirmed.",
    warranty: "Pentastar, electrical, and transmission repairs are frequently covered by extended service contracts. We document the diagnosis and coordinate with providers such as Endurance, CarShield, and AmTrust while your contract governs coverage.",
    faqs: [
      { question: "Do you repair Chrysler vehicles in Crown Point?", answer: "Yes. We diagnose and repair Chrysler vehicles — Pacifica, 300, and Town & Country — at our Crown Point, IN shop, including hybrid Pacifica electrical diagnosis." },
      { question: "Why is my Chrysler 3.6 misfiring?", answer: "Early Pentastar engines had cylinder-head issues; later ones can develop rocker-arm and lifter wear. We confirm the cylinder and mechanism with data before recommending repair." },
      { question: "Can you diagnose a Pacifica electrical problem?", answer: "Yes. We scan the modules and test the circuits before recommending parts, including on the plug-in hybrid. We tell you what the system is reporting first." },
      { question: "Do you handle Chrysler extended warranty claims?", answer: "Yes. We document findings and work with your warranty administrator on covered repairs. Coverage follows your contract." },
      { question: "Can you diagnose my Chrysler the same day?", answer: "Many Chrysler diagnostics finish the same day. Call (219) 262-2711 with the model and symptoms so we can prepare." },
    ],
    relatedServices: [
      { href: "/services/engine-repair", label: "Engine repair" },
      { href: "/services/electrical-diagnostics", label: "Electrical diagnostics" },
      { href: "/services/transmission-repair", label: "Transmission repair" },
      { href: "/services/ac-heating-repair", label: "A/C and heating repair" },
    ],
    relatedSymptoms: [
      { href: "/car-wont-start-crown-point-in", label: "Car won't start help" },
      { href: "/transmission-slipping-crown-point-in", label: "Transmission slipping help" },
    ],
  },
  {
    slug: "dodge-repair-crown-point-in",
    make: "Dodge",
    title: "Dodge Repair Crown Point IN | R Complete Auto Care",
    description: "Dodge and Ram diagnostics and repair in Crown Point, IN — Hemi lifter tick, Pentastar, 8-speed, and exhaust manifold bolts. (219) 262-2711.",
    eyebrow: "Independent Dodge service in Crown Point",
    heading: "Dodge Repair and Diagnostics in Crown Point, IN",
    tldr: "R Complete Auto Care diagnoses and repairs Dodge and Ram vehicles in Crown Point, IN — Charger, Challenger, Durango, Journey, and Ram trucks. We know Hemi and Pentastar patterns, handle extended-warranty claims, and serve Northwest Indiana.",
    intro: "Dodge's Charger, Challenger, Durango, and Journey — along with Ram trucks — pair strong engines with heavy real-world use. We confirm the engine and transmission before testing, because a lifter tick, an exhaust leak, or a shudder each leads a different investigation.",
    problems: [
      { name: "5.7L Hemi lifter tick and MDS concerns", detail: "The Hemi's Multi-Displacement System lifters and camshaft can wear and cause a tick, misfire, or dead cylinder on Charger, Challenger, Durango, and Ram. We confirm the affected cylinder with scan and mechanical data before recommending lifter and camshaft work." },
      { name: "3.6L Pentastar valvetrain and cooling concerns", detail: "The V6 in many Dodge models can develop misfires, oil-filter-housing leaks, and cooling issues. We verify the cylinder and inspect the leak source before recommending repair." },
      { name: "8-speed and older transmission concerns", detail: "The ZF-based 8-speed and earlier automatics can shudder or shift harshly, often tied to fluid and control condition. We road test, inspect fluid, and scan before recommending a service or repair." },
      { name: "Exhaust manifold bolts and leaks", detail: "Broken exhaust manifold bolts and manifold leaks create ticking and exhaust smell on some engines. We locate the leak and broken hardware before repair." },
      { name: "HVAC blend-door and electrical concerns", detail: "Blend-door actuators, HVAC faults, and electrical concerns also appear across the lineup. We test the actuator or circuit rather than replacing parts by guess." },
    ],
    warningSigns: [
      "Lifter tick, misfire, or a cylinder dropping out",
      "Ticking or exhaust smell from a manifold leak",
      "Shudder or harsh shifts from the transmission",
      "Oil or coolant leak, or overheating",
      "Inconsistent heat or cooling from one side of the vents",
    ],
    diagnostic: "We confirm the engine and transmission, review history, and road test when safe. Testing can include scan and misfire data, mechanical valvetrain and manifold inspection, transmission road testing with fluid inspection, cooling-system pressure testing, and HVAC actuator or electrical circuit testing.",
    services: [
      "Hemi lifter and camshaft diagnosis",
      "Pentastar valvetrain and cooling diagnosis",
      "Transmission diagnosis and service",
      "Exhaust manifold and leak repair",
      "HVAC and electrical diagnosis",
      "Brake, suspension, and maintenance service",
    ],
    maintenance: "Dodge and Ram maintenance depends on the engine, transmission, and truck-versus-car duty, including towing. Oil, transmission-fluid, and cooling service should follow the owner's manual and vehicle-specific guidance.",
    driving: "Stop for a flashing check-engine light, overheating, an oil-pressure warning, or a severe misfire. A manifold tick or minor leak should still be inspected before it grows.",
    timing: "A visible leak or manifold check may be same-day. Lifter, transmission, or intermittent concerns can take more testing, and repair time depends on access and parts.",
    cost: "The estimate reflects the engine and transmission, diagnostic time, and parts. We test first so a Hemi tick is not treated as a simple tune-up when the valvetrain is involved.",
    warranty: "Hemi lifter, valvetrain, and transmission repairs are frequently covered by extended service contracts. We document the diagnosis and coordinate with providers like CarShield, Endurance, and SilverRock while your contract governs coverage.",
    faqs: [
      { question: "Do you repair Dodge and Ram vehicles in Crown Point?", answer: "Yes. We diagnose and repair Dodge and Ram vehicles — Charger, Challenger, Durango, Journey, and Ram trucks — at our Crown Point, IN shop." },
      { question: "What causes the tick in my Hemi?", answer: "A Hemi tick often traces to MDS lifter and camshaft wear or to broken exhaust manifold bolts. We confirm which one with scan data and inspection before recommending repair." },
      { question: "Why does my Dodge 8-speed shudder?", answer: "The ZF-based 8-speed can shudder from fluid condition or control faults. We road test and inspect the fluid before recommending a service or repair." },
      { question: "Do you handle Dodge extended warranty claims?", answer: "Yes. We document findings and work with your warranty administrator on covered engine and transmission repairs. Coverage follows your contract." },
      { question: "Can you diagnose my Dodge the same day?", answer: "Many Dodge and Ram diagnostics finish the same day. Call (219) 262-2711 with the model, engine, and symptoms so we can prepare." },
    ],
    relatedServices: [
      { href: "/services/engine-repair", label: "Engine repair" },
      { href: "/services/transmission-repair", label: "Transmission repair" },
      { href: "/services/check-engine-light", label: "Check engine light diagnostics" },
      { href: "/services/diagnostics", label: "Auto diagnostics" },
    ],
    relatedSymptoms: [
      { href: "/transmission-slipping-crown-point-in", label: "Transmission slipping help" },
      { href: "/check-engine-light-flashing-crown-point", label: "Flashing check engine light" },
    ],
  },
  {
    slug: "gmc-repair-crown-point-in",
    make: "GMC",
    title: "GMC Repair Crown Point IN | R Complete Auto Care",
    description: "GMC diagnostics and repair in Crown Point, IN — AFM/DFM lifters, 8-speed shudder, timing chains, and Duramax concerns. (219) 262-2711.",
    eyebrow: "Independent GMC service in Crown Point",
    heading: "GMC Repair and Diagnostics in Crown Point, IN",
    tldr: "R Complete Auto Care diagnoses and repairs GMC trucks and SUVs in Crown Point, IN — Sierra, Acadia, Terrain, and Yukon. We know the GM V8 and transmission patterns, handle extended-warranty claims, and serve all of Northwest Indiana.",
    intro: "GMC's Sierra, Yukon, Acadia, and Terrain share platforms with Chevrolet but earn their own following for trucks and SUVs. We confirm the engine and transmission before testing, because a lifter tick, a shudder, or a coolant concern each requires a specific investigation.",
    problems: [
      { name: "AFM/DFM lifter failure on 5.3L and 6.2L V8s", detail: "Active and Dynamic Fuel Management lifters can fail on Sierra and Yukon V8s, causing a tick, misfire, or dead cylinder. We confirm the failed cylinder with scan and mechanical data before recommending lifter and camshaft work." },
      { name: "8-speed transmission shudder", detail: "The 8L90/8L45 automatic can shudder or shift harshly, often tied to fluid condition and valve-body wear. We road test, inspect fluid with the correct procedure, and scan before recommending service or repair." },
      { name: "3.6L V6 timing chain and cooling concerns", detail: "Timing-chain stretch, water-pump leaks, and intake gaskets appear on some 3.6L Acadia and Terrain engines. A stretched chain sets timing codes, so we verify with data before major work." },
      { name: "Duramax diesel injection and emissions concerns", detail: "Diesel Sierra trucks can present injection, CP4 pump, or emissions faults. We scan the powertrain and test fuel and emissions systems before recommending costly diesel repairs." },
      { name: "A/C condenser and HVAC concerns", detail: "A/C condensers and HVAC actuators can fail on GM trucks and SUVs. We measure system performance and test the electrical command before condemning a component." },
    ],
    warningSigns: [
      "Lifter tick, misfire, or a cylinder dropping out",
      "Shudder or harsh shifts from the automatic transmission",
      "Coolant loss, overheating, or a sweet smell",
      "Diesel warning lights, rough running, or reduced power",
      "Weak A/C cooling or inconsistent vent temperature",
    ],
    diagnostic: "We confirm the engine and transmission, review history, and road test when safe. Testing can include scan and misfire data, transmission road testing with fluid inspection, cooling-system pressure testing, diesel fuel and emissions diagnosis, and A/C performance and electrical testing.",
    services: [
      "V8 lifter and camshaft diagnosis",
      "Automatic-transmission diagnosis and service",
      "Timing-chain and cooling-system repair",
      "Duramax diesel diagnosis",
      "A/C and HVAC diagnosis",
      "Brake, suspension, and maintenance service",
    ],
    maintenance: "GMC maintenance depends on the engine — gas or Duramax diesel — the transmission, and truck-versus-SUV duty including towing. Service intervals should follow the owner's manual and vehicle-specific information.",
    driving: "Stop for overheating, an oil-pressure warning, a flashing check-engine light, a severe misfire, or a transmission slipping into traffic. Diesel warning lights should be assessed promptly to protect emissions components.",
    timing: "A visible leak or wear item may be same-day. Lifter, timing, diesel, or intermittent transmission concerns can take more testing, and repair time depends on access and parts.",
    cost: "The estimate reflects the engine and transmission, diagnostic depth, and parts. Diesel and V8 lifter work in particular require confirmation before a plan, so we test first.",
    warranty: "AFM lifter, timing, transmission, and diesel repairs are frequently covered by extended service contracts. We document the diagnosis and coordinate with providers like Endurance, CarShield, and AmTrust while your contract governs coverage.",
    faqs: [
      { question: "Do you repair GMC vehicles in Crown Point?", answer: "Yes. We diagnose and repair GMC trucks and SUVs — Sierra, Yukon, Acadia, and Terrain — at our Crown Point, IN shop, including Duramax diesel diagnosis." },
      { question: "My GMC V8 has a lifter tick — what is it?", answer: "On 5.3L and 6.2L engines, AFM/DFM lifters can collapse and cause a tick or misfire. We confirm the affected cylinder with data and mechanical testing before recommending repair." },
      { question: "Can you diagnose a Duramax diesel?", answer: "Yes. We scan the powertrain and test fuel, injection, and emissions systems before recommending diesel repairs, so you know the cause before authorizing work." },
      { question: "Do you handle GMC extended warranty claims?", answer: "Yes. We document findings and work with your warranty administrator on covered repairs. Coverage and authorization follow your contract." },
      { question: "Can you diagnose my GMC the same day?", answer: "Many GMC diagnostics finish the same day. Call (219) 262-2711 with the model, engine, and symptoms so we can prepare." },
    ],
    relatedServices: [
      { href: "/services/engine-repair", label: "Engine repair" },
      { href: "/services/transmission-repair", label: "Transmission repair" },
      { href: "/services/ac-heating-repair", label: "A/C and heating repair" },
      { href: "/services/diagnostics", label: "Auto diagnostics" },
    ],
    relatedSymptoms: [
      { href: "/car-overheating-crown-point-in", label: "Car overheating help" },
      { href: "/transmission-slipping-crown-point-in", label: "Transmission slipping help" },
    ],
  },
  {
    slug: "hyundai-repair-crown-point-in",
    make: "Hyundai",
    title: "Hyundai Repair Crown Point IN | R Complete Auto Care",
    description: "Hyundai diagnostics and repair in Crown Point, IN — Theta II engine concerns, GDI carbon, oil consumption, and catalytic faults. (219) 262-2711.",
    eyebrow: "Independent Hyundai service in Crown Point",
    heading: "Hyundai Repair and Diagnostics in Crown Point, IN",
    tldr: "R Complete Auto Care diagnoses and repairs Hyundai cars and SUVs in Crown Point, IN — Elantra, Sonata, Tucson, and Santa Fe. We know Theta II and GDI patterns, handle extended-warranty claims, and serve all of Northwest Indiana.",
    intro: "Hyundai's Elantra, Sonata, Tucson, and Santa Fe offer strong value, and several engines have well-known service patterns worth diagnosing carefully. We confirm the exact engine before testing, because a knock, oil use, or a check-engine light each requires its own investigation.",
    problems: [
      { name: "Theta II 2.0T/2.4 GDI engine concerns", detail: "Some Theta II engines are known for bearing wear that can cause a knock, stalling, or seizure, and many are covered by manufacturer campaigns. We evaluate the noise, check for knock-sensor codes, and document findings before recommending a path." },
      { name: "GDI intake-valve carbon buildup", detail: "Gasoline direct-injection engines can accumulate intake-valve carbon that causes misfires, rough idle, or hesitation. We verify the condition through data and inspection rather than assuming every rough idle is the same fix." },
      { name: "Oil consumption and low-oil warnings", detail: "Certain Hyundai engines consume oil and can trigger low-oil warnings or engine noise. We measure consumption over distance and inspect before assuming an internal repair." },
      { name: "Catalytic converter and emissions faults", detail: "Catalyst-efficiency and fuel-trim codes appear on some engines and can trace to the converter, sensors, or an upstream cause. We test the data before condemning a converter." },
      { name: "Electrical, ABS, and dual-clutch concerns", detail: "ABS module, electrical, and dual-clutch transmission concerns also appear across the lineup. We test the specific system rather than replacing components by guess." },
    ],
    warningSigns: [
      "Engine knock, ticking, or stalling",
      "Low-oil warnings or oil level dropping",
      "Rough idle, misfire, or hesitation",
      "Check-engine light with a catalyst or fuel-trim code",
      "ABS or warning lights and electrical faults",
    ],
    diagnostic: "We confirm the engine, review history and any open campaigns, and road test when safe. Testing can include scan and freeze-frame data, knock-sensor and misfire analysis, an oil-consumption measurement, intake inspection for carbon, and catalytic or electrical circuit testing as the evidence requires.",
    services: [
      "Theta II engine noise and knock diagnosis",
      "GDI carbon and misfire diagnosis",
      "Oil-consumption diagnosis",
      "Catalytic and emissions diagnosis",
      "Electrical, ABS, and transmission diagnosis",
      "Brake, suspension, and maintenance service",
    ],
    maintenance: "Hyundai maintenance depends on the engine and transmission, and GDI engines benefit from attentive oil service. We follow the owner's manual and vehicle-specific information, and we note any relevant manufacturer campaigns during inspection.",
    driving: "Stop for engine knock, stalling in traffic, overheating, an oil-pressure warning, or a flashing check-engine light. Address recurring low-oil warnings promptly to protect the engine.",
    timing: "A visible concern may be same-day. Engine-noise, carbon, or intermittent electrical diagnosis can take more testing, and repair time depends on access and parts.",
    cost: "The estimate reflects the engine, diagnostic depth, and parts. Because some failures are covered by campaigns or warranties, documentation matters, so we test and record findings first.",
    warranty: "Engine, catalytic, and transmission repairs are frequently covered by manufacturer campaigns or extended service contracts. We document the diagnosis and coordinate with administrators such as CarShield, Endurance, and CARS Protection Plus while your contract or campaign decides coverage.",
    faqs: [
      { question: "Do you repair Hyundai vehicles in Crown Point?", answer: "Yes. We diagnose and repair Hyundai cars and SUVs — Elantra, Sonata, Tucson, and Santa Fe — at our Crown Point, IN shop." },
      { question: "My Hyundai engine is knocking — what does that mean?", answer: "Some Theta II engines develop bearing wear that causes a knock, and many are covered by manufacturer campaigns. We evaluate the noise and document findings before recommending a path." },
      { question: "Does my Hyundai GDI engine need a carbon cleaning?", answer: "Maybe. Direct-injection engines can build intake-valve carbon, but a rough idle has other causes too. We verify with data and inspection before recommending service." },
      { question: "Do you handle Hyundai warranty and campaign claims?", answer: "Yes. We document findings and work with your warranty administrator; for covered engine campaigns, our documentation supports the claim. Coverage follows the program terms." },
      { question: "Can you diagnose my Hyundai the same day?", answer: "Many Hyundai diagnostics finish the same day. Call (219) 262-2711 with the model, engine, and symptoms so we can prepare." },
    ],
    relatedServices: [
      { href: "/services/engine-repair", label: "Engine repair" },
      { href: "/services/check-engine-light", label: "Check engine light diagnostics" },
      { href: "/services/electrical-diagnostics", label: "Electrical diagnostics" },
      { href: "/services/oil-change-maintenance", label: "Oil change and maintenance" },
    ],
    relatedSymptoms: [
      { href: "/check-engine-light-flashing-crown-point", label: "Flashing check engine light" },
      { href: "/car-wont-start-crown-point-in", label: "Car won't start help" },
    ],
  },
  {
    slug: "kia-repair-crown-point-in",
    make: "Kia",
    title: "Kia Repair Crown Point IN | R Complete Auto Care",
    description: "Kia diagnostics and repair in Crown Point, IN — Theta II engine concerns, GDI carbon, oil consumption, and catalytic faults. (219) 262-2711.",
    eyebrow: "Independent Kia service in Crown Point",
    heading: "Kia Repair and Diagnostics in Crown Point, IN",
    tldr: "R Complete Auto Care diagnoses and repairs Kia cars and SUVs in Crown Point, IN — Optima, Sorento, Sportage, and Soul. We know Theta II and GDI patterns, handle extended-warranty claims, and serve all of Northwest Indiana.",
    intro: "Kia's Optima, Sorento, Sportage, and Soul share much of their engineering with Hyundai and bring strong value with a few well-known service patterns. We confirm the exact engine before testing, because a knock, oil use, or a check-engine light each requires its own investigation.",
    problems: [
      { name: "Theta II 2.0T/2.4 GDI engine concerns", detail: "Some Theta II engines used in the Optima, Sorento, and Sportage are known for bearing wear that can cause a knock, stalling, or seizure, with many covered by manufacturer campaigns. We evaluate the noise and document findings before recommending a path." },
      { name: "GDI intake-valve carbon buildup", detail: "Gasoline direct-injection engines can accumulate intake-valve carbon that causes misfires, rough idle, or hesitation. We verify with data and inspection rather than assuming every rough idle is the same fix." },
      { name: "Oil consumption and low-oil warnings", detail: "Certain Kia engines consume oil and can trigger low-oil warnings or engine noise. We measure consumption over distance and inspect before assuming an internal repair." },
      { name: "Catalytic converter and emissions faults", detail: "Catalyst-efficiency and fuel-trim codes appear on some engines and can trace to the converter, sensors, or an upstream cause. We test the data before condemning a converter." },
      { name: "Electrical, dual-clutch, and A/C concerns", detail: "Dual-clutch transmission, electrical, and A/C concerns also appear across the lineup. We test the specific system rather than replacing components by guess." },
    ],
    warningSigns: [
      "Engine knock, ticking, or stalling",
      "Low-oil warnings or oil level dropping",
      "Rough idle, misfire, or hesitation",
      "Check-engine light with a catalyst or fuel-trim code",
      "Transmission hesitation or weak A/C cooling",
    ],
    diagnostic: "We confirm the engine, review history and any open campaigns, and road test when safe. Testing can include scan and freeze-frame data, knock-sensor and misfire analysis, an oil-consumption measurement, intake inspection for carbon, and catalytic, transmission, or electrical testing as the evidence requires.",
    services: [
      "Theta II engine noise and knock diagnosis",
      "GDI carbon and misfire diagnosis",
      "Oil-consumption diagnosis",
      "Catalytic and emissions diagnosis",
      "Dual-clutch, electrical, and A/C diagnosis",
      "Brake, suspension, and maintenance service",
    ],
    maintenance: "Kia maintenance depends on the engine and transmission, and GDI engines benefit from attentive oil service. We follow the owner's manual and vehicle-specific information, and we note any relevant manufacturer campaigns during inspection.",
    driving: "Stop for engine knock, stalling in traffic, overheating, an oil-pressure warning, or a flashing check-engine light. Address recurring low-oil warnings promptly to protect the engine.",
    timing: "A visible concern may be same-day. Engine-noise, carbon, or intermittent electrical diagnosis can take more testing, and repair time depends on access and parts.",
    cost: "The estimate reflects the engine, diagnostic depth, and parts. Because some failures are covered by campaigns or warranties, documentation matters, so we test and record findings first.",
    warranty: "Engine, catalytic, and transmission repairs are frequently covered by manufacturer campaigns or extended service contracts. We document the diagnosis and coordinate with administrators such as Endurance, CarShield, and AmTrust while your contract or campaign decides coverage.",
    faqs: [
      { question: "Do you repair Kia vehicles in Crown Point?", answer: "Yes. We diagnose and repair Kia cars and SUVs — Optima, Sorento, Sportage, and Soul — at our Crown Point, IN shop." },
      { question: "My Kia engine is knocking — what does that mean?", answer: "Some Theta II engines develop bearing wear that causes a knock, and many are covered by manufacturer campaigns. We evaluate the noise and document findings before recommending a path." },
      { question: "Does my Kia GDI engine need a carbon cleaning?", answer: "Maybe. Direct-injection engines can build intake-valve carbon, but a rough idle has other causes too. We verify with data and inspection before recommending service." },
      { question: "Do you handle Kia warranty and campaign claims?", answer: "Yes. We document findings and work with your warranty administrator; for covered engine campaigns, our documentation supports the claim. Coverage follows the program terms." },
      { question: "Can you diagnose my Kia the same day?", answer: "Many Kia diagnostics finish the same day. Call (219) 262-2711 with the model, engine, and symptoms so we can prepare." },
    ],
    relatedServices: [
      { href: "/services/engine-repair", label: "Engine repair" },
      { href: "/services/check-engine-light", label: "Check engine light diagnostics" },
      { href: "/services/transmission-repair", label: "Transmission repair" },
      { href: "/services/oil-change-maintenance", label: "Oil change and maintenance" },
    ],
    relatedSymptoms: [
      { href: "/check-engine-light-flashing-crown-point", label: "Flashing check engine light" },
      { href: "/car-wont-start-crown-point-in", label: "Car won't start help" },
    ],
  },
  {
    slug: "bmw-repair-crown-point-in",
    make: "BMW",
    title: "BMW Repair Crown Point IN | R Complete Auto Care",
    description: "BMW diagnostics and repair in Crown Point, IN — oil leaks, timing chains, turbo and HPFP, cooling system, and VANOS. (219) 262-2711.",
    eyebrow: "Independent BMW service in Crown Point",
    heading: "BMW Repair and Diagnostics in Crown Point, IN",
    tldr: "R Complete Auto Care diagnoses and repairs BMW cars and SUVs in Crown Point, IN — 3 Series, 5 Series, X3, and X5. We know common oil-leak, cooling, and turbo patterns, handle extended-warranty claims, and serve Northwest Indiana.",
    intro: "BMW's 3 Series, 5 Series, X3, and X5 reward precise diagnosis, and several patterns recur across the turbocharged inline engines. We identify the exact engine before testing, because an oil leak, a cooling concern, or a turbo fault each requires its own careful investigation.",
    problems: [
      { name: "Oil leaks: valve cover and oil-filter-housing gaskets", detail: "Valve-cover and oil-filter-housing gaskets commonly leak on BMW engines, sometimes onto hot components. We confirm the leak source and whether it reaches the belt or exhaust before recommending the repair." },
      { name: "Timing chain and guides on N20/N26 engines", detail: "Some 2.0L turbo engines can wear timing-chain guides, setting timing codes or noise. We verify with scan data and inspection before recommending timing work, which is significant labor." },
      { name: "Turbo, wastegate, and HPFP on N54/N55", detail: "Turbocharged inline engines can develop wastegate rattle, turbo faults, and high-pressure-fuel-pump issues causing rough running or long cranks. We test boost, fuel pressure, and misfire data before condemning a component." },
      { name: "Cooling system: water pump, thermostat, expansion tank", detail: "BMW cooling components are often plastic and fail over time, risking overheating. We pressure-test the system and identify the failed part rather than replacing the whole system by default." },
      { name: "VANOS and direct-injection carbon", detail: "VANOS variable-valve-timing solenoids and intake-valve carbon can cause rough running, codes, or reduced performance. We evaluate the data and inspect before recommending cleaning or component repair." },
    ],
    warningSigns: [
      "Oil smell, smoke, or visible leakage",
      "Timing-chain noise or a timing-related code",
      "Rough running, long cranks, or reduced power",
      "Overheating or coolant loss",
      "Check-engine light with VANOS or misfire codes",
    ],
    diagnostic: "We confirm the engine, review history, and road test when safe. Testing can include full BMW-capable scans and freeze-frame data, leak inspection, a cooling-system pressure test, boost and fuel-pressure testing, and VANOS or misfire analysis as the evidence requires.",
    services: [
      "Oil-leak and gasket repair",
      "Timing-chain and guide diagnosis",
      "Turbo, wastegate, and HPFP diagnosis",
      "Cooling-system repair",
      "VANOS and carbon diagnosis",
      "Brake, suspension, and electrical service",
    ],
    maintenance: "BMW maintenance depends on the engine and driving conditions, and turbocharged direct-injection engines benefit from attentive oil and cooling service. We use BMW-specific oil specifications and vehicle information rather than a generic schedule.",
    driving: "Stop for overheating, an oil-pressure warning, heavy smoke, or a flashing check-engine light. A minor gasket seep should still be inspected before oil reaches hot components.",
    timing: "A visible leak or cooling check may be same-day. Timing-chain, turbo, or intermittent electrical diagnosis can take more testing, and repair time depends on access and parts.",
    cost: "The estimate reflects the engine, whether the repair requires significant access such as timing work, diagnostic time, and parts. We confirm the cause first so labor-intensive jobs are not recommended prematurely.",
    warranty: "Oil-leak, cooling, timing, and turbo repairs are frequently covered by extended service contracts. We document the diagnosis and coordinate with providers such as Endurance, CARS Protection Plus, and CarShield while your contract governs coverage.",
    faqs: [
      { question: "Do you repair BMW vehicles in Crown Point?", answer: "Yes. We diagnose and repair BMW cars and SUVs — 3 Series, 5 Series, X3, and X5 — at our Crown Point, IN shop, using BMW-capable scan tools." },
      { question: "Why does my BMW leak oil?", answer: "Valve-cover and oil-filter-housing gaskets are common BMW leak points. We confirm the source and whether oil reaches hot components before recommending the repair." },
      { question: "My BMW turbo engine runs rough — what causes it?", answer: "On N54/N55 engines, wastegate, turbo, or high-pressure-fuel-pump faults can cause rough running or long cranks. We test boost, fuel pressure, and misfire data before condemning a part." },
      { question: "Do you handle BMW extended warranty claims?", answer: "Yes. We document the diagnosis and work with your warranty administrator on covered repairs. Coverage and authorization follow your contract." },
      { question: "Can you diagnose my BMW the same day?", answer: "Many BMW diagnostics finish the same day. Call (219) 262-2711 with the model, engine, and symptoms so we can prepare." },
    ],
    relatedServices: [
      { href: "/services/engine-repair", label: "Engine repair" },
      { href: "/services/electrical-diagnostics", label: "Electrical diagnostics" },
      { href: "/services/check-engine-light", label: "Check engine light diagnostics" },
      { href: "/services/ac-heating-repair", label: "A/C and heating repair" },
    ],
    relatedSymptoms: [
      { href: "/car-overheating-crown-point-in", label: "Car overheating help" },
      { href: "/check-engine-light-flashing-crown-point", label: "Flashing check engine light" },
    ],
  },
  {
    slug: "mercedes-benz-repair-crown-point-in",
    make: "Mercedes-Benz",
    title: "Mercedes-Benz Repair Crown Point IN | R Complete Auto Care",
    description: "Mercedes-Benz diagnostics and repair in Crown Point, IN — oil leaks, engine mounts, transmission conductor plate, and Airmatic. (219) 262-2711.",
    eyebrow: "Independent Mercedes-Benz service in Crown Point",
    heading: "Mercedes-Benz Repair and Diagnostics in Crown Point, IN",
    tldr: "R Complete Auto Care diagnoses and repairs Mercedes-Benz cars and SUVs in Crown Point, IN — C-Class, E-Class, GLC, and GLE. We know common oil-leak, transmission, and suspension patterns, handle extended-warranty claims, and serve Northwest Indiana.",
    intro: "Mercedes-Benz's C-Class, E-Class, GLC, and GLE combine refinement with complex systems that reward careful diagnosis. We identify the exact engine and transmission before testing, because an oil leak, a shift concern, or a suspension fault each requires its own investigation.",
    problems: [
      { name: "Oil leaks and engine mounts", detail: "Valve-cover, camshaft-adjuster, and oil-cooler-seal leaks are common, and hydraulic engine mounts can collapse and cause vibration. We confirm the leak source and mount condition before recommending repair." },
      { name: "Transmission conductor plate and valve body", detail: "The 722-series automatic can develop conductor-plate and valve-body faults causing limp mode, harsh shifts, or leaks. We scan the transmission and inspect before recommending internal work." },
      { name: "Airmatic air-suspension faults", detail: "Air-suspension struts, compressors, and lines can leak and cause a sagging corner or ride-height warnings on equipped models. We test the system and locate the leak before replacing components." },
      { name: "Camshaft adjusters and balance-shaft concerns", detail: "Camshaft-adjuster solenoids and, on some older M272/M273 engines, balance-shaft wear can set timing codes. We verify with scan data before recommending these repairs." },
      { name: "Cooling, thermostat, and electrical concerns", detail: "Thermostats, cooling components, and electrical or module faults also appear as these vehicles age. We pressure-test the cooling system and test circuits before condemning parts." },
    ],
    warningSigns: [
      "Oil leaks or a vibration through the body at idle",
      "Harsh shifting, limp mode, or a transmission leak",
      "A corner sitting low or a ride-height warning",
      "Check-engine light with camshaft or timing codes",
      "Overheating or coolant loss",
    ],
    diagnostic: "We confirm the engine and transmission, review history, and road test when safe. Testing can include Mercedes-capable scans and freeze-frame data, leak inspection, transmission scanning and inspection, air-suspension testing, and cooling-system pressure testing as the evidence requires.",
    services: [
      "Oil-leak and engine-mount repair",
      "Transmission conductor-plate and valve-body diagnosis",
      "Airmatic air-suspension diagnosis",
      "Camshaft-adjuster and timing diagnosis",
      "Cooling-system and electrical diagnosis",
      "Brake, suspension, and maintenance service",
    ],
    maintenance: "Mercedes-Benz maintenance depends on the engine and transmission, and these vehicles benefit from Mercedes-specific fluids and attentive service. We use the vehicle-specific information rather than a generic schedule.",
    driving: "Stop for overheating, an oil-pressure warning, transmission limp mode, or a suspension fault that affects control. A minor leak should still be inspected before it worsens.",
    timing: "A visible leak or suspension check may be same-day. Transmission, timing, or intermittent electrical diagnosis can take more testing, and repair time depends on access and parts.",
    cost: "The estimate reflects the engine and transmission, whether the repair requires significant access, diagnostic time, and parts. We confirm the cause first so complex jobs are not recommended prematurely.",
    warranty: "Oil-leak, transmission, suspension, and cooling repairs are frequently covered by extended service contracts. We document the diagnosis and coordinate with providers such as Endurance, CARS Protection Plus, and CarShield while your contract governs coverage.",
    faqs: [
      { question: "Do you repair Mercedes-Benz vehicles in Crown Point?", answer: "Yes. We diagnose and repair Mercedes-Benz cars and SUVs — C-Class, E-Class, GLC, and GLE — at our Crown Point, IN shop, using Mercedes-capable scan tools." },
      { question: "Why is my Mercedes in limp mode?", answer: "The 722-series transmission can enter limp mode from conductor-plate or valve-body faults, among other causes. We scan the transmission and inspect before recommending internal work." },
      { question: "Can you fix a sagging Mercedes air suspension?", answer: "Yes. Airmatic struts, compressors, and lines can leak. We test the system and locate the leak before replacing components so the right part is repaired." },
      { question: "Do you handle Mercedes-Benz extended warranty claims?", answer: "Yes. We document the diagnosis and work with your warranty administrator on covered repairs. Coverage and authorization follow your contract." },
      { question: "Can you diagnose my Mercedes-Benz the same day?", answer: "Many Mercedes-Benz diagnostics finish the same day. Call (219) 262-2711 with the model, engine, and symptoms so we can prepare." },
    ],
    relatedServices: [
      { href: "/services/engine-repair", label: "Engine repair" },
      { href: "/services/transmission-repair", label: "Transmission repair" },
      { href: "/services/suspension-steering", label: "Suspension and steering" },
      { href: "/services/electrical-diagnostics", label: "Electrical diagnostics" },
    ],
    relatedSymptoms: [
      { href: "/car-overheating-crown-point-in", label: "Car overheating help" },
      { href: "/transmission-slipping-crown-point-in", label: "Transmission slipping help" },
    ],
  },
];

// Honda is served by its own dedicated cluster (see lib/honda-pages.ts); we link
// to that hub from the make cross-links so the whole make family interlinks.
export const HONDA_MAKE_LINK: MakeLink = { href: "/honda-repair-crown-point-in", label: "Honda" };

export const MAKE_PAGES = makes;

export function getMakePage(slug: string): MakePageData {
  const page = MAKE_PAGES.find((entry) => entry.slug === slug);
  if (!page) throw new Error(`Unknown make page: ${slug}`);
  return page;
}

// Directory used by the /services index, footer, and cross-links.
export const MAKE_DIRECTORY: MakeLink[] = [
  HONDA_MAKE_LINK,
  ...MAKE_PAGES.map((page) => ({ href: `/${page.slug}`, label: page.make })),
];
