export type Faq = { q: string; a: string };

type ServiceFaqConfig = {
  name: string;
  problem: string;
  symptoms: string;
  diagnosis: string;
  unsafe: string;
  maintenance: string;
};

export const serviceFaqConfig: Record<string, ServiceFaqConfig> = {
  "check-engine-light": { name: "check engine light diagnostics", problem: "an emissions, ignition, fuel, sensor, or mechanical fault", symptoms: "a warning light, rough running, reduced power, stalling, or poor fuel economy", diagnosis: "a full-system scan followed by circuit, mechanical, and live-data tests", unsafe: "A flashing light or severe drivability problem requires you to stop driving; a steady light should be diagnosed promptly.", maintenance: "timely maintenance and repairing small air, fuel, or ignition faults" },
  diagnostics: { name: "automotive diagnostics", problem: "a mechanical, electrical, network, or software-related vehicle fault", symptoms: "warning lights, noises, leaks, intermittent operation, poor performance, or unusual behavior", diagnosis: "symptom verification, a complete scan, visual inspection, measurements, and system-specific tests", unsafe: "Safety warnings, overheating, low oil pressure, severe noises, or major drivability changes mean you should stop and call for guidance.", maintenance: "scheduled inspections and addressing new symptoms early" },
  "electrical-diagnostics": { name: "electrical diagnostics", problem: "low voltage, excessive resistance, an open or shorted circuit, a failed component, or a communication fault", symptoms: "intermittent accessories, dim lights, warning messages, blown fuses, battery drain, or a no-start", diagnosis: "battery and charging tests, voltage-drop measurements, wiring-diagram analysis, and circuit testing under load", unsafe: "Smoke, heat, a burning smell, repeated fuse failure, or loss of critical lighting requires immediate attention.", maintenance: "clean connections, a healthy battery, and prompt repair of water intrusion or damaged wiring" },
  "no-start-diagnostics": { name: "no-start diagnostics", problem: "a battery, starter, charging, fuel, ignition, security, wiring, or mechanical fault", symptoms: "clicking, slow cranking, normal cranking without starting, or intermittent failure", diagnosis: "classifying the failure, testing battery capacity and voltage drop, then verifying starter, fuel, spark, compression, and module data as needed", unsafe: "Do not repeatedly crank the engine or attempt roadside wiring repairs; arrange a tow when the vehicle cannot start reliably.", maintenance: "battery testing, clean connections, and investigating slow or intermittent starts early" },
  "engine-repair": { name: "engine repair", problem: "lubrication, cooling, ignition, fuel, timing, sealing, or internal mechanical failure", symptoms: "knocking, smoke, overheating, oil consumption, misfires, leaks, or loss of power", diagnosis: "scan data, fluid and pressure checks, compression or leak-down testing, and targeted mechanical inspection", unsafe: "Stop driving for low oil pressure, overheating, loud knocking, heavy smoke, or a flashing check-engine light.", maintenance: "correct oil, coolant service, and repairing leaks or overheating promptly" },
  "transmission-repair": { name: "transmission repair", problem: "fluid pressure, solenoid, valve-body, clutch, bearing, torque-converter, control, or internal wear", symptoms: "slipping, delayed engagement, harsh shifts, shuddering, leaks, noises, or a transmission warning", diagnosis: "fluid inspection, a full module scan, live-data review, pressure or electrical testing, and a road test when safe", unsafe: "Do not continue driving if the transmission slips, loses a gear, leaks heavily, overheats, or cannot engage reliably.", maintenance: "the manufacturer-specified fluid and service interval, plus early diagnosis of leaks or shift changes" },
  "brake-repair": { name: "brake repair", problem: "worn friction material, hydraulic leakage, seized hardware, rotor damage, contaminated fluid, or an electronic control fault", symptoms: "squealing, grinding, vibration, pulling, a soft pedal, longer stops, or a brake warning", diagnosis: "measuring pads and rotors, checking hydraulic operation and hardware, scanning control modules, and verifying the concern", unsafe: "A soft or sinking pedal, grinding, fluid loss, pulling, or reduced stopping ability means the vehicle should not be driven.", maintenance: "regular measurement, fluid inspection, and addressing noises before components are damaged" },
  "suspension-steering": { name: "suspension and steering repair", problem: "wear or damage in shocks, struts, joints, bushings, bearings, steering components, tires, or alignment", symptoms: "clunks, wandering, pulling, vibration, uneven tire wear, looseness, or a rough ride", diagnosis: "a loaded visual inspection, play measurements, tire evaluation, alignment checks, and a road test when safe", unsafe: "Severe looseness, a sudden pull, broken parts, tire contact, or loss of steering assistance requires immediate inspection.", maintenance: "tire rotations, alignment checks, and replacing worn components before they affect related parts" },
  "oil-change-maintenance": { name: "oil change and maintenance", problem: "oil degradation, contamination, incorrect level, or overdue filters and scheduled services", symptoms: "a maintenance reminder, dark or low oil, leaks, engine noise, or reduced efficiency", diagnosis: "checking service history, fluid condition and level, filters, leaks, and manufacturer maintenance requirements", unsafe: "Stop for a red oil-pressure warning or loud engine noise; an ordinary maintenance reminder should be scheduled soon.", maintenance: "using the correct oil specification and following the vehicle maker’s time and mileage interval" },
  "ac-heating-repair": { name: "A/C and heating repair", problem: "refrigerant leakage, compressor or control failure, airflow restriction, cooling-system trouble, or an electrical fault", symptoms: "warm air, weak airflow, unusual odors, noises, fogging, or inconsistent temperature", diagnosis: "temperature and pressure measurements, leak detection, control scans, electrical tests, and cooling-system checks", unsafe: "Loss of defrost visibility or an overheating engine is a safety concern; ordinary loss of cooling usually allows careful driving.", maintenance: "running the system regularly, replacing cabin filters, and repairing small leaks before refrigerant is lost" },
  "extended-warranty-repair": { name: "extended warranty repair", problem: "a covered vehicle component may have failed under the terms of a service contract", symptoms: "any mechanical or electrical concern that may qualify under the customer’s contract", diagnosis: "documenting the symptom and failed component with the tests required to establish cause of failure", unsafe: "Driving guidance depends on the failed system; stop for safety, overheating, oil-pressure, or severe drivability concerns.", maintenance: "keeping maintenance records and following the vehicle and contract requirements" },
};

export function buildServiceFaqs(slug: string): Faq[] {
  const c = serviceFaqConfig[slug];
  if (!c) return [];
  return [
    { q: `What is ${c.name}?`, a: `${c.name[0].toUpperCase()}${c.name.slice(1)} is the process of identifying or correcting ${c.problem}. R Complete Auto Care confirms the cause before recommending parts.` },
    { q: `What commonly causes the need for ${c.name}?`, a: `Common causes include ${c.problem}. The exact cause cannot be confirmed from a symptom or trouble code alone.` },
    { q: `What symptoms indicate I may need ${c.name}?`, a: `Watch for ${c.symptoms}. New, worsening, or intermittent symptoms are worth documenting and testing.` },
    { q: `How does R Complete Auto Care diagnose this problem?`, a: `We begin with ${c.diagnosis}. We compare test results with specifications before presenting a repair plan.` },
    { q: `Can I keep driving before it is diagnosed?`, a: c.unsafe },
    { q: `How much does ${c.name} usually cost?`, a: `Cost depends on the vehicle, test time, failure, parts, and access required. We provide a transparent estimate after diagnosis and do not begin repairs without your approval.` },
    { q: `How long does ${c.name} take?`, a: `Timing depends on symptom complexity, parts availability, and repair scope. Same-day diagnostics may be available, and we explain the expected timeline before authorized work begins.` },
    { q: `Do you service both domestic and foreign vehicles?`, a: `Yes. We diagnose and service domestic, Asian, and European vehicles using procedures and information appropriate to the specific year, make, model, and system.` },
    { q: `Will a trouble code identify the failed part?`, a: `No. A code identifies a system condition detected by the vehicle. Testing is needed to distinguish wiring, mechanical, control, and component causes.` },
    { q: `Do you provide an estimate before repairs?`, a: `Yes. We explain the findings, priorities, estimate, and expected timing. No repair begins without customer approval.` },
    { q: `Can this service be covered by an extended warranty?`, a: `Possibly. Coverage depends entirely on the customer’s contract, exclusions, maintenance requirements, failure cause, and administrator authorization. We can document the diagnosis and communicate with the administrator.` },
    { q: `What can help prevent this problem?`, a: `Helpful steps include ${c.maintenance}. Prevention reduces risk but cannot eliminate normal wear or unexpected failures.` },
    { q: `What should I bring to my appointment?`, a: `Bring the vehicle, keys, relevant service records, warning details, and any extended-warranty contract or claim information. Note when the symptom occurs and what changes it.` },
    { q: `Do you offer same-day diagnostics?`, a: `Same-day diagnostics may be available depending on the schedule and complexity. Call ahead so we can set a realistic arrival and completion window.` },
    { q: `Why choose R Complete Auto Care in Crown Point?`, a: `We are a family-owned, diagnostic-first shop with experienced ASE-certified technicians, professional equipment, transparent estimates, and no repairs performed without your approval.` },
  ];
}
