import type { IntegrationAdapter,SyncBatch,SyncContext } from "../contracts"; import { IntegrationUnavailableError } from "../contracts"; import { getJson,digits,asDate } from "../http"; import { getPrisma } from "@/lib/prisma";
type TekmetricRecord=Record<string,unknown>&{id?:string|number;updatedAt?:string};
type TekmetricPage={data?:TekmetricRecord[];nextCursor?:string;hasMore?:boolean};
const resourceEnv={customers:"TEKMETRIC_CUSTOMERS_URL",vehicles:"TEKMETRIC_VEHICLES_URL",repairOrders:"TEKMETRIC_REPAIR_ORDERS_URL",estimates:"TEKMETRIC_ESTIMATES_URL",appointments:"TEKMETRIC_APPOINTMENTS_URL"} as const;
const RO_STATUSES=["DRAFT","WAITING_APPROVAL","WAITING_PARTS","IN_REPAIR","READY_FOR_PICKUP","COMPLETED","CANCELLED"] as const;
type RoStatus=typeof RO_STATUSES[number];
function toRoStatus(value:unknown):RoStatus{const s=String(value??"DRAFT").toUpperCase().replace(/\s+/g,"_");return (RO_STATUSES as readonly string[]).includes(s)?s as RoStatus:"DRAFT";}
export class TekmetricAdapter implements IntegrationAdapter<TekmetricRecord>{readonly name="TEKMETRIC" as const;readonly resources=Object.keys(resourceEnv);isConfigured(){return Boolean(process.env.TEKMETRIC_API_TOKEN&&process.env.TEKMETRIC_CUSTOMERS_URL)}
 async pull(resource:string,{cursor,signal}:SyncContext):Promise<SyncBatch<TekmetricRecord>>{const key=resourceEnv[resource as keyof typeof resourceEnv];const endpoint=key&&process.env[key];const token=process.env.TEKMETRIC_API_TOKEN;if(!endpoint||!token)throw new IntegrationUnavailableError(this.name,`approved ${resource} endpoint is not configured`);const url=new URL(endpoint);if(cursor.cursor)url.searchParams.set("cursor",cursor.cursor);if(cursor.highWaterMark)url.searchParams.set("updatedSince",cursor.highWaterMark.toISOString());const page=await getJson<TekmetricPage>({provider:this.name,token,url:url.toString(),signal});const records=page.data??[];return{records,next:{cursor:page.nextCursor,highWaterMark:records.reduce((latest,r)=>{const date=asDate(r.updatedAt,latest);return date>latest?date:latest},cursor.highWaterMark??new Date(0))},hasMore:Boolean(page.hasMore&&page.nextCursor)}}
 async persist(resource:string,records:TekmetricRecord[]){const db=getPrisma();let written=0;for(const record of records){const externalId=String(record.id??"");if(!externalId)continue;
  if(resource==="customers"){const firstName=String(record.firstName??"Unknown"),lastName=String(record.lastName??"Customer"),phone=String(record.phone??record.mobilePhone??"");const existing=await db.externalRecordLink.findUnique({where:{provider_entityType_externalId:{provider:"TEKMETRIC",entityType:"customer",externalId}}});const customer=existing?.customerId?await db.customer.update({where:{id:existing.customerId},data:{firstName,lastName,phone,normalizedPhone:digits(phone)}}):await db.customer.create({data:{firstName,lastName,phone,normalizedPhone:digits(phone)}});await db.externalRecordLink.upsert({where:{provider_entityType_externalId:{provider:"TEKMETRIC",entityType:"customer",externalId}},create:{provider:"TEKMETRIC",entityType:"customer",externalId,customerId:customer.id,externalUpdatedAt:asDate(record.updatedAt)},update:{customerId:customer.id,externalUpdatedAt:asDate(record.updatedAt),syncedAt:new Date()}});written++;continue;}
  const customerExternalId=String(record.customerId??"");const customerLink=customerExternalId?await db.externalRecordLink.findUnique({where:{provider_entityType_externalId:{provider:"TEKMETRIC",entityType:"customer",externalId:customerExternalId}}}):null;if(!customerLink?.customerId)continue;
  if(resource==="vehicles"){const vin=String(record.vin??"");if(!vin)continue;await db.vehicle.upsert({where:{vin},create:{customerId:customerLink.customerId,vin,year:Number(record.year??0),make:String(record.make??"Unknown"),model:String(record.model??"Unknown"),trim:record.trim?String(record.trim):null,mileage:record.mileage?Number(record.mileage):null},update:{customerId:customerLink.customerId,year:Number(record.year??0),make:String(record.make??"Unknown"),model:String(record.model??"Unknown"),trim:record.trim?String(record.trim):null,mileage:record.mileage?Number(record.mileage):null}});written++;continue;}
  if(resource==="repairOrders"){const vin=String(record.vin??"");const vehicle=vin?await db.vehicle.findUnique({where:{vin}}):await db.vehicle.findFirst({where:{customerId:customerLink.customerId}});if(!vehicle)continue;const number=String(record.number??record.repairOrderNumber??externalId);const status=toRoStatus(record.status);const order=await db.repairOrder.upsert({where:{number},create:{number,customerId:customerLink.customerId,vehicleId:vehicle.id,status,concern:String(record.concern??record.description??"Imported from Tekmetric"),laborTotal:Number(record.laborTotal??0),partsTotal:Number(record.partsTotal??0),taxTotal:Number(record.taxTotal??0),total:Number(record.total??0),grossProfit:Number(record.grossProfit??0)},update:{status,laborTotal:Number(record.laborTotal??0),partsTotal:Number(record.partsTotal??0),taxTotal:Number(record.taxTotal??0),total:Number(record.total??0),grossProfit:Number(record.grossProfit??0)}});await db.externalRecordLink.upsert({where:{provider_entityType_externalId:{provider:"TEKMETRIC",entityType:"repairOrder",externalId}},create:{provider:"TEKMETRIC",entityType:"repairOrder",externalId,customerId:customerLink.customerId,repairOrderId:order.id},update:{customerId:customerLink.customerId,repairOrderId:order.id,syncedAt:new Date()}});written++;continue;}
  if(resource==="estimates"){const repairOrderExternalId=String(record.repairOrderId??"");const orderLink=repairOrderExternalId?await db.externalRecordLink.findUnique({where:{provider_entityType_externalId:{provider:"TEKMETRIC",entityType:"repairOrder",externalId:repairOrderExternalId}}}):null;await db.estimate.upsert({where:{source_externalId:{source:"TEKMETRIC",externalId}},create:{source:"TEKMETRIC",externalId,customerId:customerLink.customerId,repairOrderId:orderLink?.repairOrderId,number:String(record.number??externalId),status:String(record.status??"OPEN"),total:Number(record.total??0),approvedTotal:Number(record.approvedTotal??0)},update:{repairOrderId:orderLink?.repairOrderId,status:String(record.status??"OPEN"),total:Number(record.total??0),approvedTotal:Number(record.approvedTotal??0)}});written++;continue;}
  if(resource==="appointments"){const startsAt=asDate(record.startsAt??record.startTime);await db.appointment.upsert({where:{source_externalId:{source:"TEKMETRIC",externalId}},create:{source:"TEKMETRIC",externalId,customerId:customerLink.customerId,service:String(record.service??record.reason??"Service appointment"),startsAt,durationMinutes:Number(record.durationMinutes??60),notes:record.notes?String(record.notes):null},update:{service:String(record.service??record.reason??"Service appointment"),startsAt,durationMinutes:Number(record.durationMinutes??60),notes:record.notes?String(record.notes):null}});written++;}
 }
 return written;}
}
